window.PORTFOLIO_DATA = {
    "generatedAt":  "2026-06-10T11:42:47",
    "source":  "https://sites.google.com/view/25020163-phamviethoang/trang-ch%E1%BB%A7",
    "owner":  "Phạm Việt Hoàng",
    "course":  "Nhập môn Công nghệ số và Ứng dụng Trí tuệ nhân tạo",
    "pages":  [
                  {
                      "slug":  "home",
                      "section":  "Trang chủ",
                      "title":  "Portfolio",
                      "description":  "Chào mừng đến với Portfolio học tập cá nhân của em.\nWebsite này được xây dựng nhằm tổng hợp các sản phẩm học tập, minh chứng thực hành và cảm nhận cá nhân của em trong học phần Nhập môn Công nghệ số và Ứng dụng Trí tuệ nhân tạo.\nThông qua Portfolio, em trình bày quá trình rèn luyện các kỹ năng như",
                      "sourceUrl":  "https://sites.google.com/view/25020163-phamviethoang/trang-ch%E1%BB%A7",
                      "text":  [
                                   "Chào mừng đến với Portfolio học tập cá nhân của em.",
                                   "Website này được xây dựng nhằm tổng hợp các sản phẩm học tập, minh chứng thực hành và cảm nhận cá nhân của em trong học phần Nhập môn Công nghệ số và Ứng dụng Trí tuệ nhân tạo.",
                                   "Thông qua Portfolio, em trình bày quá trình rèn luyện các kỹ năng như quản lý thông tin, tìm kiếm và đánh giá tài liệu, viết prompt hiệu quả, hợp tác trực tuyến, sáng tạo nội dung bằng AI và sử dụng AI có trách nhiệm.",
                                   "Điểm nổi bật của Portfolio",
                                   "• Hệ thống hóa đầy đủ 6 bài tập thực hành trong học phần.",
                                   "• Có minh chứng trực quan cho từng hoạt động học tập.",
                                   "• Thể hiện quá trình ứng dụng công cụ số và trí tuệ nhân tạo vào học tập.",
                                   "• Có phần tự đánh giá, bài học kinh nghiệm và định hướng phát triển cá nhân.",
                                   "I. 👤 Giới thiệu",
                                   "Thông tin cá nhân, mục tiêu học tập và định hướng phát triển.",
                                   "II. 📚 Dự án học tập",
                                   "Tổng hợp 6 bài tập, minh chứng và nhận xét cá nhân.",
                                   "III. ✅ Tổng kết",
                                   "Kỹ năng tích lũy được, khó khăn và bài học kinh nghiệm."
                               ],
                      "images":  [
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUAMW55vaKb-rhdA8EcGAk-BCIf39lJiSXnwXUruIcYzsqw4gCZzTOoh8TVI75iKywxaa-JbxyQo8PRb37VKB29ap6mDjaYhreRCrzb5v5vlJNnDu3T6Zhe5P0AbEvv3Rw9l8rsF0RHj8EF432xH5-Q6CwrwOBmPsPyYYMqEyE9K1JkiPO1FuUB0O6oFaP257AXsK8VRjzK1GldGapMZjO-kBHCRGHa-13O0U_CZ=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUBfrY3bvJJKQLbcHzQB-ZZLV782fKpdYmxPZogx2nbkWPe3T0Ew9zXMkH0PjEgeEf0TT21_a8-_znHUbsneFJApzc24vxwBzXuUYYW8JFVjSX7olbegdKcRqGZnnSNhRS73k3Ft_sMeW1mFrb9aWx50ox0FMjlsVvwnq8uJQid94rlBHbCxgYEaZXkCVXHlDBQtTzspdH87Rz8W8218q2qQ23aJfct1bhAydBTE=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUDLTqZFLScyuca9tBPQNyZTkGd-HA5nSAfsaUbk8xAJ-Jl4RGWVfj61CXEztp57GaQSLh-Cd5r9azqqQV7HUmznL4OzV-IpqMJ_v4CwPNiDxse9vry7SSkq8aOd7tCvk-by07rg-otW07kQsJY_oAsfmQtxup1wGH9bPNPVBnbdCvIo2xB-dk-K3QCfdnz-rRCLe5mR5i80p3SkZrEyH-b6sFic-P9GDzF-v_c3=w1280"
                                 ]
                  },
                  {
                      "slug":  "intro",
                      "section":  "I. Giới thiệu",
                      "title":  "Portfolio - I. Giới thiệu",
                      "description":  "Giới thiệu bản thân\nXin chào, em là Phạm Việt Hoàng, hiện là sinh viên ngành Công nghệ thông tin. Em quan tâm đến công nghệ số, trí tuệ nhân tạo và các công cụ hỗ trợ học tập hiện đại.\nPortfolio này được xây dựng nhằm tổng hợp các sản phẩm học tập của em trong học phần Nhập môn Công nghệ số và Ứng",
                      "sourceUrl":  "https://sites.google.com/view/25020163-phamviethoang/i-giới-thiệu",
                      "text":  [
                                   "Giới thiệu bản thân",
                                   "Xin chào, em là Phạm Việt Hoàng, hiện là sinh viên ngành Công nghệ thông tin. Em quan tâm đến công nghệ số, trí tuệ nhân tạo và các công cụ hỗ trợ học tập hiện đại.",
                                   "Portfolio này được xây dựng nhằm tổng hợp các sản phẩm học tập của em trong học phần Nhập môn Công nghệ số và Ứng dụng Trí tuệ nhân tạo. Thông qua Portfolio, em muốn thể hiện quá trình học tập, khả năng sử dụng công cụ số, kỹ năng tìm kiếm thông tin, kỹ năng làm việc trực tuyến và khả năng sử dụng AI một cách có trách nhiệm.",
                                   "Thông tin cá nhân",
                                   "Họ và tên: Phạm Việt Hoàng",
                                   "Ngành học: Công nghệ thông tin",
                                   "Lớp: IT4 - K70I",
                                   "Trường: Trường Đại học Công nghệ - Đại học Quốc gia Hà Nội",
                                   "Học phần: Nhập môn Công nghệ số và Ứng dụng Trí tuệ nhân tạo",
                                   "Kỹ năng quan tâm: Công nghệ số, trí tuệ nhân tạo, tìm kiếm thông tin, làm việc nhóm và thiết kế nội dung số.",
                                   "Kỹ năng rèn luyện trong học phần",
                                   "Kỹ năng số",
                                   "Biết cách quản lý tập tin, tìm kiếm thông tin, lưu trữ dữ liệu và sử dụng công cụ trực tuyến trong học tập.",
                                   "Trí tuệ nhân tạo",
                                   "Biết cách viết prompt, sử dụng AI để hỗ trợ học tập và kiểm tra lại thông tin do AI tạo ra.",
                                   "Làm việc nhóm",
                                   "Biết cách phối hợp trực tuyến, chia sẻ tài liệu, trao đổi thông tin và trình bày sản phẩm học tập rõ ràng hơn.",
                                   "Mục tiêu của Portfolio",
                                   "Portfolio này được thực hiện nhằm hệ thống hóa các bài tập và sản phẩm học tập trong học phần. Thông qua Portfolio, em có thể trình bày quá trình thực hiện, minh chứng kết quả, cũng như những kỹ năng đã rèn luyện được trong quá trình học.",
                                   "Ngoài ra, Portfolio còn giúp em nhìn lại quá trình học tập của bản thân, từ đó nhận ra điểm mạnh, điểm cần cải thiện và định hướng cách sử dụng công nghệ số, trí tuệ nhân tạo một cách hiệu quả hơn trong học tập.",
                                   "Định hướng phát triển cá nhân",
                                   "Trong thời gian tới, em mong muốn tiếp tục nâng cao khả năng sử dụng các công cụ số phục vụ cho học tập và công việc. Đặc biệt, em muốn tìm hiểu sâu hơn về trí tuệ nhân tạo, cách viết prompt hiệu quả và cách ứng dụng AI vào học tập một cách trung thực, có trách nhiệm.",
                                   "Bên cạnh đó, em cũng muốn cải thiện kỹ năng trình bày sản phẩm cá nhân, kỹ năng quản lý thông tin và kỹ năng làm việc nhóm trực tuyến. Đây là những kỹ năng cần thiết đối với sinh viên Công nghệ thông tin trong môi trường học tập và làm việc hiện đại.",
                                   "Thông điệp cá nhân",
                                   "Học tập trong môi trường số không chỉ là biết sử dụng công cụ, mà còn là biết lựa chọn, kiểm chứng và ứng dụng công nghệ một cách có trách nhiệm."
                               ],
                      "images":  [
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUANhimUFf0YQ1I75gXnZXVzlWIxXtINQnl-9z8lTir4sU_QhOzapMRy5MUMV67_ew9ttwIcOacGi1B22bfy7KlFjhU455EAg_uSpzwPOfYQWkijrjmiE9t9qzSEPx264pEXzxVxg2xVw76aPxhU83PGLh6OhhWv__bJU-7rgwpHAOqDp6k2dCb6Q1hkI2NzV5bJDl-GJvDF-St9O8l8uklyDaj6Enh4apGkDsl_TQ8=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUDVPdZmlkGO0KEwun9n0qPz7AT5WJ2yX_g0MuPAY3Q7lLNWCTpe42nk8O-yL0QNGadrT_OTSq7OhrHB070gS1qoXt9z8mJcLwPBaHvuSQfdfUrZWJGtE67VGGpCJTuZWFAfegUGkgWD5WYu92H3tQdp9Gm4tSp88V7ytfmzzow8R9jUgbS9w5KdlQvDoFH92hrBa7FYtjCvuvltl7Rt6klTfFesJdquWYLQKiuI=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUAfOyWcZjFk1S44h0Fau3H6fq3_SeKSPX7tgOaBk2maempwshQNjg5on7KxfTytWybKr5SgJLC13mypELk1uRboLiZGnGWP6NL32f88Z0LWzNOOMNGMmrF7AAHZOdlTEGNbiuYSumInGr8OnCO8gcugTIEDh6cX7Eq9eStRLH2_WNwbzSTdGfDpBQOQ53_j_0jA0izaOwBPqCDcivKcjJa2pCjVfpQnDacVvPTa=w1280"
                                 ]
                  },
                  {
                      "slug":  "projects",
                      "section":  "II. Dự án học tập",
                      "title":  "Portfolio - II. Dự án học tập",
                      "description":  "Trang này tổng hợp các bài tập thành phần em đã thực hiện trong học phần Nhập môn Công nghệ số và Ứng dụng Trí tuệ nhân tạo. Mỗi bài tập được trình bày ở một trang riêng nhằm giúp nội dung rõ ràng, dễ theo dõi và thuận tiện cho việc xem minh chứng.\nCác bài tập được trình bày theo cấu trúc thống",
                      "sourceUrl":  "https://sites.google.com/view/25020163-phamviethoang/ii-dự-án-học-tập",
                      "text":  [
                                   "Trang này tổng hợp các bài tập thành phần em đã thực hiện trong học phần Nhập môn Công nghệ số và Ứng dụng Trí tuệ nhân tạo. Mỗi bài tập được trình bày ở một trang riêng nhằm giúp nội dung rõ ràng, dễ theo dõi và thuận tiện cho việc xem minh chứng.",
                                   "Các bài tập được trình bày theo cấu trúc thống nhất gồm: mục tiêu, công cụ sử dụng, quá trình thực hiện, kết quả đạt được, minh chứng và nhận xét cá nhân. Qua đó, Portfolio thể hiện quá trình em rèn luyện kỹ năng công nghệ số, kỹ năng tìm kiếm thông tin, kỹ năng hợp tác trực tuyến và kỹ năng sử dụng AI có trách nhiệm.",
                                   "Danh sách bài tập thành phần",
                                   "Mỗi bài tập dưới đây thể hiện một nhóm kỹ năng trọng tâm trong học phần.",
                                   "Bài 1",
                                   "Thao tác cơ bản với tập tin và thư mục",
                                   "Bài 2",
                                   "Tìm kiếm và đánh giá thông tin học thuật",
                                   "Bài 3",
                                   "Viết Prompt hiệu quả cho các tác vụ học tập",
                                   "Bài 4",
                                   "Sử dụng công cụ hợp tác trực tuyến",
                                   "Bài 5",
                                   "Sử dụng AI tạo sinh hỗ trợ sáng tạo nội dung",
                                   "Bài 6",
                                   "Sử dụng AI có trách nhiệm trong học tập"
                               ],
                      "images":  [
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUBMgxLwAVjJi8KOgZllaRzNDq6YK4knOGo2Y-U5f2BAa1DpbrkL0p-8gU84IFHP5TCEPV4m2pMqXQ7Tz50POuThINev7iG2TaM9IyWikUhflfRrO8ijchE8_KuQ3BxSgCWsFL6Syb5OfwJxfKOsDUZhSqdkXDsIwvx2wZASXd8mU3cLlVOh871SW3emIxOnAu7h242PYosaJYpDLvlCuTtS_xQ9lNZA2jN5ZUYczHo=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUDHp2hDyTqjwmjBHEJ07ogd4B670TooBt32nwj6xj8AV2h7ZaJ5-7qbuUc2qIjbPGdnqpRdM9cF19CNkMRdLCipDDYn2SwA8MOJF47YXUt8CDSYa4TrK2PBzMjHg00PE_c3BBBf4hhW9YEcQPPGozuLLtvxg-kegD3AIztLb_Ro7nWpDOieg8spOIFen6ZcLfN-3K20HNRUxhn-5C7JJYTcUxjrTBiVETVixLmBLzY=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUB_yD87DvZJB2rlsVusD71mm4OON2s1RA0I5Y48BJHIOPFcOutExQWzhMfq3vtfQ6ImfKJCYlL7bYTf_AyDbkHHu8KWNsgTnyp9HjRzFXR8Djy7uQIykQt1V3r1LTfwAxgvUiQliFrn9Dmr1inXNe335inXJ1hMHUOGzKy3F8GF8AsHGVUkflHWrpCftC65I7YpbsTSEO-P_EUpWbzZyuHCqzqYf_OBOlmILtGYhbs=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUArRrOL8pp0PtT9aMiJiQLnGYIk0Mm_MIPgd2FX01BMjki-QHDL54GZEVnq8XfD9pbU3g0TStCl7XIBkZBIgZrNOjyrOwszFXp5MxlZeSfGZZS_YFBqvluZIxejUpU4iuiII9LnzZ47nKwycOh0oPl2Cd59hltOHIx-qGAYbJkhD8Q-sqn4SttTopf_Gm7fB1HUWOifFzAG-1Sk0m7QYavQX38e059l4zEoImQ_gUY=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUBHxEr-18FH3HylTUdDjA49hWdfxDpMqKTdUsjZ8JIOkzXzxUQ8jwysa5nQezSmvR73zUPKbXhyLeHty_l4uVV7A_rzRhtLV2MvGuYTNHPSsyKLDToGVJTS_4oGmsIHYR5kFOfwjUqQPhPiiXsRTF5lTlh1S3i0eaodqH0PupSrMZ8lw8fvwbr-LXylZ1QRYssCnGGVRfFfE7JjThg8TqlrwxLeM_LzHxkLCjK539w=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUCVFLA008d4lmvkriZ7kSKBn2nkznvZH-I_kc-qA0wRbAeZbPYLiyoQsmtlGn5_-UMZ-yOrSY9L3YS9Wb4Q-9D6wiHkdW0SX53F6DXs1M4hdxONRzB2OSSDTTKOF88CaDbSkng9Mpo9MyvNRUXVJKPxY9fcIFc6sWAPFDpw553EBEWnBMS6-U62_MFKSH-yxDmVLDzDO6wcZUECBB4ODBajHSDuw1gPaNp05CrEHLs=w1280"
                                 ]
                  },
                  {
                      "slug":  "bai-1",
                      "section":  "Bài 1",
                      "title":  "Portfolio - Bài 1 : Thao tác cơ bản với tập tin và thư mục",
                      "description":  "Giới thiệu bài tập\nBài tập này tập trung vào việc thực hành các thao tác cơ bản với tập tin và thư mục trên hệ điều hành Windows thông qua File Explorer. Nội dung thực hiện bao gồm tạo thư mục, tạo và đổi tên tệp, sao chép, di chuyển, xóa và khôi phục dữ liệu.\nThông qua bài tập, kỹ năng tổ chức dữ",
                      "sourceUrl":  "https://sites.google.com/view/25020163-phamviethoang/ii-dự-án-học-tập/bài-1-thao-tác-cơ-bản-với-tập-tin-và-thư-mục",
                      "text":  [
                                   "Bài 1: Thao tác cơ bản với tập tin và thư mục",
                                   "Giới thiệu bài tập",
                                   "Bài tập này tập trung vào việc thực hành các thao tác cơ bản với tập tin và thư mục trên hệ điều hành Windows thông qua File Explorer. Nội dung thực hiện bao gồm tạo thư mục, tạo và đổi tên tệp, sao chép, di chuyển, xóa và khôi phục dữ liệu.",
                                   "Thông qua bài tập, kỹ năng tổ chức dữ liệu cá nhân được rèn luyện theo hướng rõ ràng, khoa học và an toàn hơn, đồng thời tạo nền tảng cho việc quản lý tài liệu học tập trong môi trường số.",
                                   "Thông tin bài tập",
                                   "Chủ đề: Thao tác cơ bản với tập tin và thư mục",
                                   "Công cụ sử dụng: File Explorer trên Windows",
                                   "Khu vực thực hành: Thư mục Documents",
                                   "Nội năng chính: Tạo thư mục, đổi tên, sao chép, di chuyển, xóa và khôi phục tập tin",
                                   "Mục tiêu và kỹ năng đạt được",
                                   "Tổ chức dữ liệu: Biết cách tạo cây thư mục rõ ràng, có phân cấp.",
                                   "Đặt tên tập tin: Biết đặt tên dễ hiểu, thống nhất và phù hợp nội dung.",
                                   "Thao tác dữ liệu: Thực hiện được sao chép, di chuyển, đổi tên và xóa tập tin.",
                                   "An toàn dữ liệu: Phân biệt được xóa tạm thời, khôi phục và xóa vĩnh viễn.",
                                   "I. Khởi tạo không gian làm việc",
                                   "Thiết lập một thư mục thực hành riêng trong Documents để tạo không gian lưu trữ dữ liệu rõ ràng, dễ quản lý và hạn chế nhầm lẫn với các thư mục khác.",
                                   "1. Mở File Explorer bằng tổ hợp phím Windows + E hoặc nhấp vào biểu tượng thư mục trên thanh tác vụ.",
                                   "2.Truy cập vào This PC, sau đó chọn thư mục Documents để tạo khu vực thực hành. Nếu có ổ đĩa riêng ngoài ổ hệ thống, có thể thực hiện trên ổ D: hoặc E:.",
                                   "3.Tạo thư mục mới bằng thao tác chuột phải → New → Folder.",
                                   "4.Nhấp đúp vào thư mục để truy cập vào không gian thực hành.",
                                   "II. Tạo và đổi tên tệp tin",
                                   "Thực hiện thao tác tạo tệp văn bản và đổi tên tệp để rèn luyện kỹ năng đặt tên dữ liệu rõ ràng, thống nhất và dễ nhận biết.",
                                   "1. Tạo tệp văn bản mới bằng thao tác chuột phải vào khoảng trống → New → Text Document.",
                                   "2. Nhấp chuột phải vào tệp GhiChu.txt → chọn Rename.",
                                   "III. Tạo thư mục con để phân loại dữ liệu",
                                   "Tạo thư mục con nhằm phân loại dữ liệu theo mục đích sử dụng, giúp quá trình lưu trữ và tìm kiếm tài liệu thuận tiện hơn.",
                                   "1. Trong thư mục thực hành, nhấp chuột phải vào khoảng trống → New → Folder.",
                                   "2. Đặt tên thư mục con là TaiLieu để lưu trữ các tệp văn bản trong quá trình thực hành.",
                                   "IV. Sao chép dữ liệu — Copy \u0026 Paste",
                                   "Thực hiện thao tác Copy \u0026 Paste để tạo bản sao của tệp tin, đồng thời giữ nguyên tệp gốc ở vị trí ban đầu.",
                                   "1. Chọn tệp GhiChuQuanTrong.txt, sau đó nhấp chuột phải → Copy hoặc sử dụng tổ hợp phím Ctrl + C.",
                                   "2. Mở thư mục TaiLieu, nhấp chuột phải vào khoảng trống → Paste hoặc sử dụng tổ hợp phím Ctrl + V.",
                                   "3. Kiểm tra kết quả: tệp GhiChuQuanTrong.txt xuất hiện trong thư mục TaiLieu, trong khi tệp gốc vẫn còn ở thư mục ban đầu.",
                                   "V. Di chuyển dữ liệu — Cut \u0026 Paste",
                                   "Thực hiện thao tác Cut \u0026 Paste để di chuyển tệp từ vị trí cũ sang vị trí mới, qua đó phân biệt rõ sự khác nhau giữa sao chép và di chuyển dữ liệu.",
                                   "1. Quay lại thư mục thực hành và tạo một tệp văn bản mới tên là DiChuyen.txt.",
                                   "2. Chọn tệp DiChuyen.txt, nhấp chuột phải → Cut hoặc sử dụng tổ hợp phím Ctrl + X.",
                                   "3. Mở thư mục TaiLieu, nhấp chuột phải vào khoảng trống → Paste hoặc sử dụng tổ hợp phím Ctrl + V.",
                                   "4. Kiểm tra kết quả: tệp DiChuyen.txt chỉ còn xuất hiện trong thư mục TaiLieu và không còn ở vị trí cũ.",
                                   "VI. Xóa dữ liệu tạm thời — Delete",
                                   "Thực hiện thao tác Delete để kiểm tra cơ chế xóa tạm thời của Windows, trong đó tệp bị xóa sẽ được chuyển vào Recycle Bin và vẫn có thể khôi phục.",
                                   "1. Mở thư mục TaiLieu và chọn tệp GhiChuQuanTrong.txt.",
                                   "2. Nhấp chuột phải vào tệp GhiChuQuanTrong.txt → chọn Delete.",
                                   "3. Kiểm tra kết quả: tệp được chuyển vào Recycle Bin thay vì bị xóa vĩnh viễn ngay lập tức.",
                                   "VII. Xóa dữ liệu vĩnh viễn — Shift + Delete",
                                   "Thực hiện thao tác Shift + Delete để nhận biết cơ chế xóa vĩnh viễn và rủi ro khi dữ liệu không được chuyển vào Recycle Bin.",
                                   "1. Chọn tệp DiChuyen.txt trong thư mục TaiLieu.",
                                   "2. Nhấn giữ phím Shift và nhấn Delete.",
                                   "3. Quan sát hộp thoại cảnh báo xác nhận xóa vĩnh viễn.",
                                   "4. Nếu xác nhận, tệp sẽ bị xóa trực tiếp và không đi qua Recycle Bin.",
                                   "VIII. Khôi phục dữ liệu từ Recycle Bin",
                                   "Thực hiện thao tác Restore để kiểm tra khả năng khôi phục tệp đã bị xóa tạm thời bằng Delete.",
                                   "1. Mở Recycle Bin trên màn hình Desktop.",
                                   "2. Tìm tệp đã xóa bằng thao tác Delete.",
                                   "3. Nhấp chuột phải vào tệp cần khôi phục → chọn Restore.",
                                   "4. Kiểm tra kết quả: tệp được đưa trở lại vị trí ban đầu.",
                                   "IX. So sánh Delete và Shift + Delete",
                                   "Sau khi thực hiện hai thao tác xóa dữ liệu, có thể so sánh Delete và Shift + Delete để lựa chọn cách xử lý phù hợp trong từng trường hợp.",
                                   "Delete:",
                                   "• Tệp được chuyển vào Recycle Bin.",
                                   "• Có thể khôi phục nếu chưa dọn thùng rác.",
                                   "• Phù hợp khi muốn xóa tạm thời hoặc chưa chắc chắn.",
                                   "• Mức độ rủi ro thấp hơn.",
                                   "Shift + Delete:",
                                   "• Tệp bị xóa trực tiếp khỏi vị trí lưu trữ.",
                                   "• Không đi qua Recycle Bin.",
                                   "• Khó khôi phục bằng thao tác thông thường.",
                                   "• Chỉ nên dùng khi chắc chắn không còn cần dữ liệu.",
                                   "• Mức độ rủi ro cao hơn.",
                                   "X. Tổng kết và bài học kinh nghiệm",
                                   "Từ quá trình thực hành, em rút ra một số bài học quan trọng về tổ chức dữ liệu, đặt tên tệp và đảm bảo an toàn khi thao tác với tập tin.",
                                   "Quản lý tập tin và thư mục là kỹ năng nền tảng khi sử dụng máy tính trong học tập và làm việc. Một cấu trúc thư mục rõ ràng giúp dữ liệu được tổ chức khoa học, dễ tìm kiếm và hạn chế nhầm lẫn.",
                                   "Việc đặt tên tệp và thư mục cần được thực hiện thống nhất, ngắn gọn và phản ánh đúng nội dung. Điều này giúp quá trình lưu trữ và sử dụng tài liệu trở nên hiệu quả hơn.",
                                   "Bên cạnh đó, cần phân biệt rõ giữa Delete và Shift + Delete để tránh mất dữ liệu quan trọng. Delete phù hợp với thao tác xóa tạm thời vì có thể khôi phục từ Recycle Bin, trong khi Shift + Delete chỉ nên dùng khi chắc chắn không còn cần tệp đó.",
                                   "Bài học cốt lõi: Quản lý dữ liệu tốt không chỉ là thao tác kỹ thuật, mà còn là thói quen làm việc khoa học cần duy trì trong học tập và các dự án công nghệ sau này."
                               ],
                      "images":  [
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUBofLiPoHUZzYX0MOnphBf1Rq7yS8X-Ur_bX-EfVCHlpUyCN44Kvx8iHhChK7c9D78caCJLuWlZnFA3nV7WHJvBM5-jJ8xr_PONo627WuRdDdwAImfZ-gY9fObMfDWR3cRbtt8HwFCY2uZts4SU7Jx8JAfnBWaC_PKAUs6XYqNzXgvXhGF5kLnQb3pQ9mWbW29zdClrkSnEDjU5U2W9Zr7ZFTibHJuRER5K2UHIOBY=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUC2757hIUY3O8n6q5Dhp6HyvHznrqdaX7VhP_bjDYiGSZPOmJr7Vm8MhELVycbodPXK74PWjU5z2NH7jyMNTBTVFTQARqZ4nHbOOfwIfQdo2TViOYg_Z18rKeWHHKzZE5lGVjYoCQlsr1HswT-66wocmANvJtnFneUImeiOOdheEeYOoN-kNR-xTbohxWaAR4Hd-2JBlzOi1Vu_d8xg0JnMPBn7xp5Irhe1pnBbZwc=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUCIhLQeHU2RjZQ-CzSfBsnOU3N8f1TkQPCIgrcH5bUiL-drjs0GDbxdwYrJBMAMg6rL4zka_XqD3iZJGRNKJk115wxyJp3oHKKiFy-u7nOV1gnklW5Dkl4qBTVf3aUwkq1BW0hDa_l_eiDSB7g33TDCVWe0dKI6uGoXLUOPj7w9oGJmaFs7Poqif39vGPdatyIzQ6jqPS4AgysfDMFySSl5aLCR0GpbHXu-cO-n=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUDzjQqTXkccFonD-uE12NamxaxnvOR1SmQSmd4MA2g99uxXlZ6iIYLCN_ayHuQfhMa_V0_jWOwLmx9202rlAwCfaaRrZSCRuToLRHxivRM9inVUjF-eDoDWLyvwCLPSTBc5tDifDElTvsQvup1Dt_NBMsif2HD6C71EE8YdUoUQHsiwx1yehiKtgRZ-w-QMcpXX500b6tLI74Y3OHlEy7e5gIurpaVBj9c-5gZ0LSk=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUA3e9YhJUtaitk00z27L7HRxzOEuwHTzL_1OL53nvGlNHn5QsOBDMeb-p2ZDIMaFfoKi0fPHhUoX4jv9zZZYCl5jTAQ0X7kg66lpPxEdjeYzTza2X9s_M3REN9oHi6SDdwZPbGYQXmufsjZ7lfh77jsZRYQ-qwOjoxpgMZOjbNIA4JzCCKAfVRsuuS1SgP797fxBUMgE7iYWRIhB-ydhVIhgmM1EFay3ZbYH3PM=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUDPw6ww8px5Z9fSnleEhhDzQNUsFsV0fzdRkddPkq5QfFr8nGypHlrh2Sv0VYD2yCYQM8FDlOZfyHmsnYwb92iiNK-TzLPt-IoejZN-EWY-NwDrmhTdBoNp0v1PaCIwgyESkv91WctpXssm_Vc4OuB3QFK_b9DbaBj8QiT3GQCmwU3bwz-p6K6Do11maMZ9pcNHNRISIoaHPz-KwXsrr2ZyWTwzKWnIbDA10a__=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUDSYKhgg0QSWDb5zYPlMJP1ONhXuD69Gl_KvftkFE48pDX6Q2hBTijmRrFPsmfVplrkQP_jgS1gVvTlgtVXemxd1TYFwdiVZqJVcFTMTc5XdRWet9Brg3QRK_f_8rx0xPP96zh8z6dfNbfkdMj51DCh9y8yYYRzE4XiJ2NjUC6nnyv453iTMBvai_MBq1GM81_VakWaMOocHEyvxAvHvS6JyOEdKLTk4aLx3hnruME=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUCxOLX-N-GtDi6oxcCMxipdZd9EN2wJIq6WjNA_xw0mBx3N8c7Xl5Hpdp7yXP6PMDHj2AuQ_i_4eQxXU0fNor6pi2rt-sepmSP5vmGSodAe4OT9Mew0n9z1NMFm-TYx4WUxwd78EPTTXrmwhEkayPSLy5gL5DG0G8OpONHueys5ENdZZbmzzu2dWw77wlsTkk3WwtfHKzAVn1a9c2RK2hhiCzMRvxicxuxndTqyaeE=w1280"
                                 ]
                  },
                  {
                      "slug":  "bai-2",
                      "section":  "Bài 2",
                      "title":  "Portfolio - Bài 2 : Tìm kiếm và đánh giá thông tin học thuật",
                      "description":  "Giới thiệu bài tập\nBài tập này tập trung vào việc tìm kiếm, chọn lọc và đánh giá các nguồn thông tin học thuật liên quan đến chủ đề tấn công lừa đảo Phishing qua mạng xã hội. Nội dung thực hiện bao gồm xác định chủ đề, xây dựng phạm vi tìm kiếm, lựa chọn từ khóa, thu thập tài liệu, đánh giá độ tin",
                      "sourceUrl":  "https://sites.google.com/view/25020163-phamviethoang/ii-dự-án-học-tập/bài-2-tìm-kiếm-và-đánh-giá-thông-tin-học-thuật",
                      "text":  [
                                   "Bài 2: Tìm kiếm và đánh giá thông tin học thuật",
                                   "Giới thiệu bài tập",
                                   "Bài tập này tập trung vào việc tìm kiếm, chọn lọc và đánh giá các nguồn thông tin học thuật liên quan đến chủ đề tấn công lừa đảo Phishing qua mạng xã hội. Nội dung thực hiện bao gồm xác định chủ đề, xây dựng phạm vi tìm kiếm, lựa chọn từ khóa, thu thập tài liệu, đánh giá độ tin cậy của nguồn và tổng hợp danh mục tài liệu tham khảo.",
                                   "Thông qua bài tập, kỹ năng tìm kiếm thông tin học thuật được rèn luyện theo hướng có chiến lược, có tiêu chí đánh giá rõ ràng và biết lựa chọn nguồn phù hợp cho học tập, nghiên cứu.",
                                   "Thông tin bài tập",
                                   "• Chủ đề: Các kỹ thuật tấn công lừa đảo Phishing qua mạng xã hội và phương pháp nhận diện dành cho người dùng cá nhân",
                                   "• Công cụ sử dụng: Google Scholar, IEEE, Google Search và các nguồn báo cáo an ninh mạng",
                                   "• Phạm vi tìm kiếm: Tài liệu trong giai đoạn 2021–2026",
                                   "• Nội dung chính: Tìm kiếm tài liệu, đánh giá nguồn, phân loại độ tin cậy và tổng hợp tài liệu tham khảo",
                                   "Mục tiêu và kỹ năng đạt được",
                                   "• Xác định chủ đề: Biết lựa chọn vấn đề nghiên cứu rõ ràng, có tính thực tiễn và phù hợp với ngành Công nghệ thông tin.",
                                   "• Xây dựng chiến lược tìm kiếm: Biết xác định phạm vi, nguồn tìm kiếm và từ khóa phù hợp.",
                                   "• Thu thập tài liệu: Biết khai thác nhiều loại nguồn như bài báo khoa học, báo cáo tổ chức, tạp chí chuyên ngành và nguồn chính thống.",
                                   "• Đánh giá nguồn tin: Biết đánh giá tài liệu theo các tiêu chí như tác giả, cơ quan xuất bản, phương pháp nghiên cứu, trích dẫn và tính cập nhật.",
                                   "• Tổng hợp thông tin: Biết lập bảng so sánh, phân loại độ tin cậy và rút ra kết luận từ các nguồn đã thu thập.",
                                   "I. Xác định chủ đề nghiên cứu và phạm vi tìm kiếm",
                                   "Xác định chủ đề là bước đầu tiên giúp quá trình tìm kiếm thông tin có trọng tâm, tránh thu thập tài liệu lan man hoặc không phù hợp với yêu cầu học thuật.",
                                   "1. Lựa chọn chủ đề nghiên cứu: Các kỹ thuật tấn công lừa đảo Phishing qua mạng xã hội và phương pháp nhận diện dành cho người dùng cá nhân.",
                                   "2. Xác định lý do chọn đề tài: mạng xã hội như Facebook, Zalo và TikTok ngày càng phổ biến, khiến người dùng cá nhân dễ trở thành mục tiêu của các hình thức lừa đảo trực tuyến.",
                                   "3. Giới hạn phạm vi thời gian tài liệu trong khoảng 5 năm gần đây, từ 2021 đến 2026, để bảo đảm tính cập nhật.",
                                   "Minh chứng : Chủ đề, lý do chọn đề tài và phạm vi tìm kiếm của báo cáo",
                                   "II. Xây dựng chiến lược và từ khóa tìm kiếm",
                                   "Chiến lược tìm kiếm được xây dựng bằng cách kết hợp nhiều loại nguồn và nhiều nhóm từ khóa khác nhau. Điều này giúp mở rộng phạm vi tài liệu, đồng thời tăng khả năng tìm được các nguồn có độ tin cậy cao.",
                                   "1. Lựa chọn nhóm nguồn tìm kiếm gồm: Google Scholar, IEEE, sách chuyên khảo, tạp chí khoa học, blog bảo mật và báo cáo của các cơ quan an ninh mạng.",
                                   "2. Xây dựng nhóm từ khóa tiếng Anh:",
                                   "• \"Social media phishing attacks\"",
                                   "• \"Social engineering phishing Facebook\"",
                                   "• \"Phishing detection social networks\"",
                                   "3. Xây dựng từ khóa tiếng Việt:",
                                   "• \"Nhận diện lừa đảo mạng xã hội\"",
                                   "Minh chứng : Nguồn tìm kiếm và từ khóa được sử dụng trong quá trình thu thập tài liệu.",
                                   "III. Thu thập tài liệu từ nhiều nhóm nguồn",
                                   "Việc thu thập tài liệu từ nhiều nhóm nguồn giúp tạo góc nhìn toàn diện hơn về chủ đề Phishing, bao gồm cả khía cạnh học thuật, kỹ thuật và tình hình thực tế.",
                                   "1. Thu thập các bài báo khoa học liên quan đến nhận diện tấn công Phishing bằng Machine Learning, Neural Networks và các phương pháp phát hiện tự động.",
                                   "2. Thu thập các báo cáo từ tổ chức và cơ quan an ninh mạng như APWG, Cục An toàn thông tin, Hiệp hội An ninh mạng quốc gia và NCSC.",
                                   "3. Bổ sung các nguồn mở rộng từ tạp chí chuyên ngành, blog bảo mật và các bài phân tích tình huống thực tế.",
                                   "Minh chứng : Các tài liệu được thu thập từ nhiều nhóm nguồn khác nhau.",
                                   "IV. Đánh giá độ tin cậy của tài liệu",
                                   "Các tài liệu được đánh giá dựa trên 5 tiêu chí: tác giả, cơ quan xuất bản, phương pháp nghiên cứu, trích dẫn và tính cập nhật. Cách đánh giá này giúp phân loại nguồn thông tin theo mức độ đáng tin cậy.",
                                   "1. Nhóm nguồn có độ tin cậy rất cao thường có cơ quan công bố uy tín, dữ liệu cập nhật và phương pháp rõ ràng, ví dụ APWG, NCSC, Cục An toàn thông tin hoặc các bài báo có phương pháp thực chứng.",
                                   "2. Nhóm nguồn có độ tin cậy cao hoặc khá vẫn có giá trị tham khảo, nhưng có thể tồn tại hạn chế như phạm vi dữ liệu hẹp, tài liệu hơi cũ hoặc thiên về cảnh báo chuyên môn.",
                                   "3. Việc đánh giá ưu điểm và nhược điểm của từng nguồn giúp lựa chọn tài liệu phù hợp hơn cho học tập và nghiên cứu.",
                                   "Minh chứng : Đánh giá độ tin cậy của tài liệu theo tiêu chí học thuật.",
                                   "V. Tổng hợp bảng đánh giá tài liệu",
                                   "Bảng tổng hợp giúp so sánh các tài liệu theo cùng một hệ tiêu chí, từ đó lựa chọn được nguồn phù hợp nhất cho quá trình học tập và nghiên cứu.",
                                   "Bảng đánh giá gồm các thông tin chính: tên tài liệu, tác giả, năm xuất bản, loại nguồn, đánh giá độ tin cậy, ưu điểm, nhược điểm và xếp hạng. Tổng cộng có 12 tài liệu được đưa vào bảng đánh giá.",
                                   "Minh chứng : Bảng tổng hợp đánh giá các tài liệu tham khảo.",
                                   "VI. Danh mục tài liệu tham khảo",
                                   "Danh mục tài liệu tham khảo thể hiện các nguồn đã được sử dụng trong quá trình tìm kiếm và đánh giá. Việc liệt kê tài liệu giúp tăng tính minh bạch và khả năng kiểm chứng của bài báo cáo.",
                                   "Danh mục gồm 12 nguồn, bao gồm bài báo khoa học, báo cáo tổ chức, nguồn từ cơ quan nhà nước và tạp chí chuyên ngành.",
                                   "Minh chứng : Danh mục tài liệu tham khảo được sử dụng trong báo cáo",
                                   "VII. Kết luận và bài học kinh nghiệm",
                                   "Tìm kiếm thông tin học thuật không chỉ dừng lại ở việc nhập từ khóa vào công cụ tìm kiếm. Quá trình này cần có chiến lược rõ ràng, biết lựa chọn từ khóa phù hợp, khai thác nhiều loại nguồn và đánh giá thông tin theo tiêu chí cụ thể.",
                                   "Đối với chủ đề Phishing trên mạng xã hội, việc kết hợp giữa bài báo khoa học, báo cáo tổ chức quốc tế, nguồn từ cơ quan nhà nước và tài liệu chuyên ngành giúp tạo ra góc nhìn toàn diện hơn. Các nguồn như APWG, NCSC, Cục An toàn thông tin hoặc các bài báo có phương pháp nghiên cứu rõ ràng thường có độ tin cậy cao hơn.",
                                   "Bài học cốt lõi: Một nguồn thông tin học thuật đáng tin cậy cần có tác giả hoặc tổ chức công bố rõ ràng, phương pháp minh bạch, nội dung cập nhật và có thể kiểm chứng bằng các nguồn khác."
                               ],
                      "images":  [
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUBc52uVuQqeq598r_kHJdcXISKm8u-WqzYC0WDQd6Pq8Ri76KVX0vzz4Qor-CoZoQCbc6ODpXDSQs2PA2i-bHCVomyIk_8bZN2M_YtZwX1gBQRf038KmwzFxbvtI74Ec7cWsNMhBZVoJ6kcAmW3KUWyFNtEKBVFTyPB6dX1FPmRf9ygq78-Sw7bxlE5aCDowBtQ23Mk2arcNLTEqrRh3SBZctXNFFZeIm8z6j3ircc=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUDhy2DtmaBwFxEgbSQ-p8awinxGnruXMQ4SZzvaRD-eCthSrQADIOTi8E7m504pgLcYSH_Q1o3GhvkPEHXnOdjN1Thl3pnNWV7L2CjBodFOGTNrUP8f9v6h77SL-KSYnnzxXd1RNDl44udW-LX6HE8bOlwj2J4MzHgdqsfhN3bJLoTXozwJMga1m7Gqma1VryD1Duo1FmkFxLH3bQsG5A3v_4y4D99Lx4G76-X69gM=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUDhnRR5e2yvYEt61tOh0Ro4anvnXy2Re3PCiTXp9a9kMNl6nwAQ6Zv_LPZX_WI1wJdnvP1Q-jzzOlcgSoCKJIki6Tj3jn9THAn5MRo_QxG0eowL21I6leE8Fmx4fHddVaLlnErOW7Uv3kJjqN3-jlfehQT6dwqR6y5zlQO7F3z1c1e9UQnOasC40uCjJUbM4pv95cUywjAA03Y44J9Ut84PDyceuVcSLqVb2Ogr=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUA8rDZct8vtkdChRi7ZVBWLb3kMxQlj7Y_hbkc7FsyP3V6dhqjXLW8y6bBxXnB3Fm9qqT-fjIVSpmKWvG_Cee-LL86URysQxSqkhdmwAAZz_C6DWe8SBOg4EBAzFpUN72M_84WM4y3XMy2r7S05kNv68DoClMHJzB94zWhjIr1r4S-G23JRZZHxZIWj3fRgrMQfKE3sBXIHENOrQwq3kgg3gs8TnV9WwKUBZNzHThQ=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUCryrBKesE_Z89_XsS4HTZhiVOlDsBzMm18B2EUAYWRwizkOowrOM0quCb4vmXpn5Z6ml8UDm_j5WzKilqYdZe6Iz0qOZzMcjrhR0Pb_8T03jcdVJ4Pg9u8V0_S052Hhhxc1j4doV_-wKvL4E4JOoN7QzuSd9pigEJstg0SnPCq3yDSfLy4Xr7uVw-xJ5EwMfaDwX6VC2ST7XeGVn-p3-enqMw91Q-3M80NuMYG=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUA9_Wy5_7o639ThW7S7BBidIHETZ1gxboI2enwFMpDqqh3sSXMuzU1JUAAzWGTKI4NE45L1F1T8wHjoMHhyW1fdoA3IUy5inNSXbVwB4-TTybqLrCIixPWKvqJnXHooF8N8P2mbVPqpPHoRHNOGv97qz1AJQ8-u96twaQhuYrYqztXu8B0KiRhJFBRVs4cf3Nnso2xiDYgdD5y2ia5LiuGH1yP99sewwvrBmfAc=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUC4HuP6KLOFV6OlZs0yUZqnszJ5jKIQkjNyW76O0ale8-lkOE7MSsZJSNOyfSAv_TwVMVkniM7NYSE67iIh9am-gF9aKNRkNyJYkghaDYN_KHTIPYbweZVvjIYQLI2kMJ_VJ3upCQcv9NPTXgQAjAObq5Mp7-XzelqGzPG9h4AcCf47lxCxOqX4aYYqOjomT2IEoTp2feoD2bHUyscOXcpnq2yNsC0rc0n4BF219rM=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUCJKwcP3CBhhGU6PwAjrfXgwDeIZF9TK8I6Gck-GoJaR06r0GZ5CRTNDtbgEkji_mKjv0WkZLbWJ9gvLJSZtRtrnqUh8mZAAStWlKuqbtO1xEjesYSX5YNjekpjOwCKgZNOyiYccZ_ZrRdQJZCV9en3qRDqc5SxSngRRtBlTrcdGrzRX5EsQGguARR3KW8zHvlY2Gna12WJVly-1nntGFo5kR6D9_s6khGWc146jKI=w1280"
                                 ]
                  },
                  {
                      "slug":  "bai-3",
                      "section":  "Bài 3",
                      "title":  "Portfolio - Bài 3 : Viết Prompt hiệu quả cho các tác vụ học thuật",
                      "description":  "Giới thiệu bài tập\nBài tập này tập trung vào việc rèn luyện kỹ năng viết prompt hiệu quả khi sử dụng công cụ trí tuệ nhân tạo trong học tập. Nội dung thực hiện bao gồm lựa chọn tác vụ học tập, xây dựng nhiều phiên bản prompt, thử nghiệm kết quả đầu ra và so sánh mức độ hiệu quả giữa các",
                      "sourceUrl":  "https://sites.google.com/view/25020163-phamviethoang/ii-dự-án-học-tập/bài-3-viết-prompt-hiệu-quả-cho-các-tác-vụ-học-thuật",
                      "text":  [
                                   "Bài 3: Viết Prompt hiệu quả cho các tác vụ học thuật",
                                   "Giới thiệu bài tập",
                                   "Bài tập này tập trung vào việc rèn luyện kỹ năng viết prompt hiệu quả khi sử dụng công cụ trí tuệ nhân tạo trong học tập. Nội dung thực hiện bao gồm lựa chọn tác vụ học tập, xây dựng nhiều phiên bản prompt, thử nghiệm kết quả đầu ra và so sánh mức độ hiệu quả giữa các prompt.",
                                   "Thông qua bài tập, kỹ năng giao tiếp với AI được rèn luyện theo hướng rõ ràng, có mục tiêu, có ngữ cảnh và có tiêu chí đánh giá. Đây là kỹ năng quan trọng giúp người học khai thác AI như một công cụ hỗ trợ học tập thay vì chỉ sử dụng AI để nhận câu trả lời nhanh.",
                                   "Thông tin bài tập",
                                   "• Chủ đề: Phát triển kỹ năng viết prompt hiệu quả trong học tập",
                                   "• Công cụ sử dụng: Google Gemini",
                                   "• Nội dung chính: Viết prompt, thử nghiệm kết quả, cải tiến prompt và đánh giá chất lượng đầu ra",
                                   "• Tác vụ thực hành: Tóm tắt tài liệu học thuật, giải thích khái niệm phức tạp và tạo bộ câu hỏi ôn tập",
                                   "Mục tiêu và kỹ năng đạt được",
                                   "• Xác định tác vụ học tập: Biết lựa chọn các nhiệm vụ phù hợp để AI hỗ trợ trong quá trình học tập.",
                                   "• Viết prompt cơ bản: Biết tạo câu lệnh ban đầu để yêu cầu AI thực hiện nhiệm vụ.",
                                   "• Cải tiến prompt: Biết bổ sung ngữ cảnh, vai trò, đối tượng, định dạng và ràng buộc để nâng cao chất lượng đầu ra.",
                                   "• Đánh giá kết quả AI: Biết so sánh kết quả từ các phiên bản prompt khác nhau.",
                                   "• Rút ra nguyên tắc sử dụng AI: Biết tổng hợp các mẹo viết prompt hiệu quả và sử dụng AI có mục đích.",
                                   "I. Lựa chọn và phân tích tác vụ học tập",
                                   "Việc lựa chọn tác vụ học tập giúp xác định rõ mục tiêu sử dụng AI, từ đó thiết kế prompt phù hợp với từng nhu cầu cụ thể.",
                                   "Trong bài thực hành, ba tác vụ học tập được lựa chọn gồm",
                                   "1. Tóm tắt tài liệu học thuật về chủ đề tác động của AI trong giáo dục.",
                                   "2. Giải thích một khái niệm phức tạp, cụ thể là công nghệ Blockchain.",
                                   "3. Tạo bộ câu hỏi ôn tập cho môn Khởi nghiệp kinh doanh.",
                                   "Minh chứng : Ba tác vụ học tập được lựa chọn để thử nghiệm kỹ năng viết prompt.",
                                   "II. Thử nghiệm prompt với tác vụ tóm tắt tài liệu học thuật",
                                   "Tác vụ đầu tiên tập trung vào khả năng sử dụng AI để tóm tắt nội dung học thuật. Đây là kỹ năng hữu ích khi cần xử lý nhanh các bài đọc dài hoặc tài liệu chuyên ngành.",
                                   "1. Prompt cơ bản:",
                                   "\"Tóm tắt cho tôi bài viết về Trí tuệ nhân tạo trong giáo dục.\"",
                                   "2. Prompt cải tiến:",
                                   "\"Hãy tóm tắt chủ đề ứng dụng của Trí tuệ nhân tạo trong giáo dục thành 3 đoạn văn chính, nêu rõ ưu điểm và nhược điểm.\"",
                                   "3. Prompt nâng cao:",
                                   "\"Đóng vai là một giảng viên đại học. Hãy tóm tắt chủ đề \u0027Ứng dụng AI trong giáo dục\u0027 dành cho sinh viên năm nhất chưa có nhiều kiến thức về công nghệ. Yêu cầu bắt buộc: sử dụng gạch đầu dòng, làm nổi bật 3 lợi ích cốt lõi và cung cấp ví dụ thực tế gần gũi với môi trường đại học.\"",
                                   "Minh chứng : Kết quả prompt nâng cao khi yêu cầu AI tóm tắt chủ đề ứng dụng AI trong giáo dục.",
                                   "So sánh kết quả cho thấy prompt cơ bản thường tạo ra câu trả lời còn chung chung và khó ghi nhớ. Khi bổ sung vai trò, đối tượng người đọc, định dạng trình bày và yêu cầu ví dụ thực tế, kết quả đầu ra trở nên rõ ràng, gần gũi và phù hợp hơn với mục tiêu học tập.",
                                   "III. Thử nghiệm prompt với tác vụ giải thích khái niệm Blockchain",
                                   "Tác vụ thứ hai tập trung vào khả năng dùng AI để giải thích một khái niệm công nghệ phức tạp bằng ngôn ngữ dễ hiểu.",
                                   "\"Giải thích công nghệ Blockchain là gì.\"",
                                   "\"Hãy giải thích công nghệ Blockchain hoạt động như thế nào một cách đơn giản, không sử dụng quá nhiều từ ngữ chuyên ngành IT.\"",
                                   "\"Đóng vai một người kể chuyện. Hãy giải thích khái niệm \u0027Blockchain\u0027 cho một học sinh cấp 2. Đầu tiên, hãy bắt đầu bằng một sự liên tưởng liên quan đến một cuốn sổ ghi chép điểm số dùng chung trong lớp học. Sau đó, giải thích cách cuốn sổ này ngăn chặn việc sửa điểm trái phép mà không cần giáo viên quản lý.\"",
                                   "Minh chứng : Kết quả prompt nâng cao khi AI giải thích Blockchain bằng ví dụ cuốn sổ ghi điểm chung.",
                                   "Kết quả cho thấy prompt nâng cao giúp AI chia nhỏ vấn đề và sử dụng liên tưởng gần gũi hơn. Ví dụ về cuốn sổ ghi điểm chung giúp khái niệm phân quyền và chống sửa đổi dữ liệu trong Blockchain trở nên trực quan, dễ hiểu hơn so với cách giải thích thuần kỹ thuật.",
                                   "IV. Thử nghiệm prompt với tác vụ tạo bộ câu hỏi ôn tập",
                                   "Tác vụ thứ ba tập trung vào khả năng dùng AI để tạo câu hỏi ôn tập phục vụ quá trình tự học và tự kiểm tra kiến thức.",
                                   "\"Tạo câu hỏi ôn tập môn Khởi nghiệp.\"",
                                   "\"Tạo 5 câu hỏi trắc nghiệm và 2 câu hỏi tự luận để ôn tập kiến thức môn Khởi nghiệp, cung cấp sẵn đáp án.\"",
                                   "\"Đóng vai một chuyên gia đào tạo doanh nghiệp. Hãy tạo một bài test nhỏ về \u0027Lập kế hoạch kinh doanh\u0027 để đánh giá tư duy phản biện của học viên. Bao gồm 3 câu trắc nghiệm khó, yêu cầu giải thích tại sao đáp án sai dễ gây nhầm lẫn, và 1 câu tình huống tự luận.\"",
                                   "Minh chứng : Kết quả prompt nâng cao khi AI tạo bộ câu hỏi ôn tập có yêu cầu phân tích và giải thích đáp án.",
                                   "So với prompt cơ bản, prompt nâng cao tạo ra bộ câu hỏi có chất lượng tốt hơn vì không chỉ yêu cầu đáp án đúng mà còn yêu cầu giải thích các đáp án sai dễ gây nhầm lẫn. Điều này giúp người học không chỉ ghi nhớ kiến thức mà còn rèn luyện tư duy phân tích và phản biện.",
                                   "V. So sánh các phiên bản prompt",
                                   "Việc so sánh các phiên bản prompt giúp nhận ra tác động của cách đặt câu lệnh đối với chất lượng đầu ra của AI.",
                                   "Prompt cơ bản | Câu lệnh ngắn, ít ngữ cảnh, ít ràng buộc | Kết quả thường chung chung, dễ lan man, chưa sát nhu cầu học tập",
                                   "Prompt cải tiến | Có thêm yêu cầu về độ dài, định dạng hoặc đối tượng | Kết quả rõ hơn, dễ đọc hơn, nhưng vẫn có thể thiếu chiều sâu",
                                   "Prompt nâng cao | Có vai trò, ngữ cảnh, đối tượng, ví dụ mẫu và yêu cầu cụ thể | Kết quả có cấu trúc tốt, phù hợp mục tiêu và dễ sử dụng hơn trong học tập",
                                   "VI. Phân tích lý do prompt nâng cao hiệu quả hơn",
                                   "Prompt nâng cao hiệu quả hơn vì cung cấp cho AI nhiều thông tin định hướng hơn, giúp kết quả đầu ra đúng mục tiêu và dễ sử dụng hơn.",
                                   "1. Có ngữ cảnh rõ ràng: Prompt nâng cao cho AI biết chủ đề, mục đích sử dụng và tình huống học tập cụ thể.",
                                   "2. Có vai trò cụ thể: Khi yêu cầu AI đóng vai giảng viên, người kể chuyện hoặc chuyên gia đào tạo, câu trả lời sẽ có giọng văn và mức độ chuyên môn phù hợp hơn.",
                                   "3. Có đối tượng người đọc: Việc xác định người học là sinh viên năm nhất, học sinh cấp 2 hoặc học viên kinh doanh giúp AI điều chỉnh độ khó của nội dung.",
                                   "4. Có định dạng đầu ra: Yêu cầu gạch đầu dòng, ví dụ thực tế, câu hỏi trắc nghiệm hoặc câu hỏi tình huống giúp kết quả dễ đọc và dễ sử dụng.",
                                   "5. Có ràng buộc rõ ràng: Các yêu cầu cụ thể giúp hạn chế tình trạng AI trả lời lan man hoặc không đúng trọng tâm.",
                                   "VII. Nguyên tắc viết prompt hiệu quả trong học tập",
                                   "Từ quá trình thử nghiệm, có thể rút ra một số nguyên tắc giúp viết prompt hiệu quả hơn khi sử dụng AI trong học tập.",
                                   "Nên áp dụng công thức C.R.E.A.T.E khi viết prompt:",
                                   "C - Context",
                                   ": Cung cấp bối cảnh cụ thể cho nhiệm vụ.",
                                   "R - Role",
                                   ": Chỉ định vai trò cho AI, ví dụ giảng viên, gia sư, chuyên gia hoặc người kể chuyện.",
                                   "E - Examples",
                                   ": Cung cấp ví dụ mẫu để AI hiểu cấu trúc mong muốn.",
                                   "A - Audience",
                                   ": Xác định đối tượng người đọc hoặc người học.",
                                   "T - Task \u0026 Tone",
                                   ": Nêu rõ nhiệm vụ và giọng điệu cần sử dụng.",
                                   "E - Explicit Format",
                                   ": Yêu cầu định dạng đầu ra cụ thể như bảng, gạch đầu dòng, đoạn văn hoặc danh sách.",
                                   "Minh chứng : Công thức C.R.E.A.T.E được tổng hợp sau quá trình thực hành viết prompt.",
                                   "VIII. Kết luận và bài học kinh nghiệm",
                                   "Kỹ năng viết prompt không chỉ là cách đặt câu hỏi cho AI, mà còn là cách trình bày nhiệm vụ học tập một cách rõ ràng, logic và có mục đích.",
                                   "Qua quá trình thử nghiệm, có thể nhận thấy prompt càng cụ thể thì kết quả đầu ra càng dễ sử dụng. Một prompt hiệu quả cần có ngữ cảnh, vai trò, đối tượng, nhiệm vụ, ràng buộc và định dạng trình bày rõ ràng.",
                                   "Bài học cốt lõi: AI có thể trở thành công cụ hỗ trợ học tập hiệu quả khi người học biết đặt yêu cầu đúng cách, biết kiểm tra kết quả và biết điều chỉnh prompt để phù hợp với mục tiêu học tập."
                               ],
                      "images":  [
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUCFosb8y1nGw7uvL6-JH3wv-0kIHL1t2CcdSa3SYcH_0NDBIscBJbD8fblmLqhToeovps4ewSPgBHP8yFCdsjRaT2VgnXZx6WuWz97jW7myJeNPkCAHsLuLVtqSSZqdGA1zAaX0vu4pN1TS0u8pWgqZYRG-RnYjX6tx44hIW1tjFnxfFcKQAbG_KORqAFDZRF7WvIwPoBXt_rEnYuO9ErOOrwOw7qwAFFg8S5JDB2o=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUCxCzBD74ytuGfPygYexAJVCwbb791y_MWI5cXm4qyfwX2ZxWLcN4fYqh3ZhrV0daILeTMe8lrIzfXKMOIIIAFdWY867mu_2TcRRy3Qf4rrIvE8srA9Bgmc-dR3cEY9THKHQfgil4pit92lKA0syOi1dPKZ68hZc8Zyh5VpWy5vyzNLnjP1lwnepsxm_JXz5evJyKSTF4uV8MpiwZC18Uw2TBKn9xohCHC4oYldqAU=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUDQJOlbjaVtrWYIneuUjlonE8MJAA24TwGTNkZs4ftaKMkXndq9voqJRJ-bX0pfoFnNswhmnBXgSn9b1_eZFF2NpX3qpUp6avsGCK3KwcE6Lu1Paenl8M2R0OyARVACGRN1vDWJrRs1AtbR5LWuC2s6_w9kZF6RlrEJSYuXUB6iFb6B46JNqGzy3YnsSmToUHm3eb3e6mkqOrRpguS8ASCEtkkOuV2uQ0etXpCq-Bw=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUAO2rlctizOG6L6UPlvW4RUeTZ3cNTc85r4NbvIpzDpoJ8fFXe7CzRUuoysPCCgUdMYsWFYvYI2jmlOy85vwp1LhfC4CyRzMLDwT5_E0rFS_1kO9QTnhFEyAqlf5Csgbbht2SQZVNTeTCvz3kOJwQ6zWF2PLKwbb08jJGafV2HD2tjYUXqdquJCTinmiG8spocCTyGsTLC--ay6LptjriDxlCxDSkJALCRgpz2QxtM=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUCpIjTT8cZnJXJ31mA-5h76WfC_dlB31DwJKDO4gzByL4IrnBTMe0fIZQF7-J5pMXtSEII1otOBevmYLAYdzu07BGwC-BSCiAo2Hg7Y0SNovgzgg2APiOkEgu3d0kYvIp7rf54lf_iTKK9k6zH9SbfNTBGMT-gnjSnf9faKiMcYnIftZg0pIXnGZ149MnMQ334o5UpXA9VTUkQn6brLQnKaXzxAvRDL2NWcMMKO=w1280"
                                 ]
                  },
                  {
                      "slug":  "bai-4",
                      "section":  "Bài 4",
                      "title":  "Portfolio - Bài 4 : Sử dụng công cụ hợp tác trực tuyến cho dự án nhóm",
                      "description":  "Giới thiệu bài tập\nBài tập này tập trung vào việc rèn luyện kỹ năng cộng tác trực tuyến thông qua quá trình tham gia một dự án nhóm. Nội dung thực hiện bao gồm thiết lập công cụ làm việc, phân chia nhiệm vụ, trao đổi thông tin, quản lý tài liệu và theo dõi tiến độ thực hiện.\nThông qua bài tập, kỹ",
                      "sourceUrl":  "https://sites.google.com/view/25020163-phamviethoang/ii-dự-án-học-tập/bài-4-sử-dụng-công-cụ-hợp-tác-trực-tuyến-cho-dự-án-nhóm",
                      "text":  [
                                   "Bài 4: Sử dụng công cụ hợp tác trực tuyến cho dự án nhóm",
                                   "Giới thiệu bài tập",
                                   "Bài tập này tập trung vào việc rèn luyện kỹ năng cộng tác trực tuyến thông qua quá trình tham gia một dự án nhóm. Nội dung thực hiện bao gồm thiết lập công cụ làm việc, phân chia nhiệm vụ, trao đổi thông tin, quản lý tài liệu và theo dõi tiến độ thực hiện.",
                                   "Thông qua bài tập, kỹ năng làm việc nhóm trong môi trường số được rèn luyện theo hướng chủ động, có tổ chức và có trách nhiệm. Việc sử dụng các công cụ trực tuyến giúp quá trình phối hợp trở nên rõ ràng hơn, hạn chế thất lạc thông tin và nâng cao hiệu quả hoàn thành sản phẩm nhóm.",
                                   "Thông tin bài tập",
                                   "• Chủ đề: Kỹ năng cộng tác trực tuyến",
                                   "• Dự án nhóm: Tổng quan về Trí tuệ nhân tạo hiện nay",
                                   "• Công cụ sử dụng: Trello, Google Docs, Google Drive và Discord",
                                   "• Vai trò cá nhân: Người khởi xướng và điều phối dự án",
                                   "• Nội dung chính: Thiết lập công cụ, quản lý tiến độ, giao tiếp nhóm, quản lý tài nguyên và xử lý thách thức trong quá trình làm việc nhóm",
                                   "Mục tiêu và kỹ năng đạt được",
                                   "• Tổ chức công việc nhóm: Biết thiết lập công cụ quản lý dự án và phân chia nhiệm vụ rõ ràng.",
                                   "• Cộng tác trực tuyến: Biết sử dụng các nền tảng như Google Docs, Google Drive, Trello và Discord để phối hợp với các thành viên.",
                                   "• Quản lý tài nguyên: Biết sắp xếp thư mục, đặt tên tệp và quản lý phiên bản tài liệu.",
                                   "• Giao tiếp số: Biết trao đổi, phản hồi và theo dõi thông tin trong môi trường trực tuyến.",
                                   "• Giải quyết vấn đề: Biết nhận diện thách thức khi làm việc nhóm và đề xuất giải pháp phù hợp.",
                                   "I. Tổng quan dự án và vai trò cá nhân",
                                   "Việc xác định rõ dự án và vai trò cá nhân giúp quá trình cộng tác trực tuyến có định hướng rõ ràng, từ đó mỗi thành viên có thể chủ động thực hiện nhiệm vụ được giao. Trong dự án nhóm “Tổng quan về Trí tuệ nhân tạo hiện nay”, vai trò của em là người khởi xướng và điều phối dự án. Nhiệm vụ chính là phối hợp với các thành viên thông qua công cụ trực tuyến để hoàn thành báo cáo nghiên cứu đúng hạn và bảo đảm chất lượng.",
                                   "II. Thiết lập công cụ cộng tác trực tuyến",
                                   "Các công cụ cộng tác trực tuyến được lựa chọn theo từng nhóm chức năng khác nhau, bao gồm quản lý tiến độ, soạn thảo tài liệu, lưu trữ dữ liệu và giao tiếp nhóm.",
                                   "1. Sử dụng Trello để quản lý tiến độ công việc theo dạng bảng Kanban. Các nhiệm vụ được phân chia theo trạng thái như cần làm, đang làm, cần duyệt và đã xong.",
                                   "2. Sử dụng Google Docs và Google Drive để soạn thảo, lưu trữ và chia sẻ tài liệu nhóm. Các thư mục được phân cấp rõ ràng để dễ quản lý.",
                                   "3. Sử dụng Discord để giao tiếp, trao đổi nội dung và chia nhỏ các kênh thảo luận theo từng chủ đề.",
                                   "Minh chứng : Thiết lập các công cụ cộng tác trực tuyến gồm Trello và Google Drive.",
                                   "III. Quản lý tiến độ và tương tác nhóm",
                                   "Theo dõi tiến độ và duy trì tương tác thường xuyên là yếu tố quan trọng giúp nhóm hạn chế chậm deadline và bảo đảm các nhiệm vụ được cập nhật kịp thời. Trong quá trình thực hiện dự án, tiến độ công việc được cập nhật thường xuyên trên hệ thống. Trạng thái công việc cá nhân được cập nhật ít nhất 3 lần mỗi tuần. Bên cạnh đó, các hoạt động thảo luận, phản hồi tin nhắn và góp ý trực tiếp trên tài liệu nhóm cũng được duy trì thường xuyên.",
                                   "IV. Quản lý tài nguyên và tệp tin",
                                   "Quản lý tài nguyên số giúp nhóm lưu trữ dữ liệu khoa học, tránh thất lạc tài liệu và hạn chế nhầm lẫn giữa các phiên bản trong quá trình làm việc.",
                                   "1. Hệ thống thư mục được phân chia theo cấu trúc rõ ràng, bao gồm thư mục tài liệu tham khảo, thư mục minh chứng và thư mục sản phẩm cuối.",
                                   "2. Các tệp được đặt tên theo quy tắc thống nhất nhằm thể hiện ngày tạo, nội dung và phiên bản tài liệu.",
                                   "3. Việc lưu trữ theo phiên bản giúp nhóm dễ dàng kiểm tra, chỉnh sửa và khôi phục tài liệu khi cần thiết.",
                                   "Minh chứng : Cấu trúc thư mục và quy tắc đặt tên tệp trong Google Drive.",
                                   "V. Phân tích thách thức và giải pháp",
                                   "Trong quá trình cộng tác trực tuyến, nhóm có thể gặp một số khó khăn như trôi thông tin, nhầm lẫn phiên bản tài liệu hoặc tiến độ không đồng đều. Việc nhận diện sớm các vấn đề này giúp nhóm đưa ra giải pháp phù hợp hơn.",
                                   "Các thách thức chính gồm:",
                                   "Trôi thông tin:",
                                   "Tin nhắn quá nhiều có thể khiến thành viên bỏ sót yêu cầu quan trọng.",
                                   "Xung đột phiên bản:",
                                   "Nhiều bản thảo cũ và mới dễ gây nhầm lẫn trong quá trình chỉnh sửa.",
                                   "Tiến độ không đều:",
                                   "Một số nhiệm vụ có thể bị chậm so với kế hoạch nếu không được nhắc nhở kịp thời.",
                                   "Giải pháp được áp dụng gồm sử dụng ghim tin nhắn, tạo luồng thảo luận riêng, đặt tên tệp thống nhất, dùng lịch sử phiên bản và thiết lập nhắc nhở trước deadline.",
                                   "Minh chứng : Bảng phân tích thách thức, giải pháp và minh chứng ghim thông báo trên Discord.",
                                   "VI. Đánh giá hiệu quả cộng tác trực tuyến",
                                   "Việc sử dụng nhiều công cụ trực tuyến giúp quá trình làm việc nhóm được tổ chức rõ ràng hơn, từ khâu phân công nhiệm vụ đến trao đổi thông tin và lưu trữ sản phẩm.",
                                   "Trello giúp nhóm theo dõi trạng thái công việc một cách trực quan. Google Drive hỗ trợ lưu trữ tài liệu tập trung và hạn chế thất lạc dữ liệu. Google Docs giúp các thành viên cùng chỉnh sửa nội dung và góp ý trực tiếp. Discord hỗ trợ trao đổi nhanh, tạo kênh theo chủ đề và ghim các thông báo quan trọng.",
                                   "Nhờ kết hợp các công cụ này, quá trình cộng tác trở nên minh bạch hơn, thông tin quan trọng được phản hồi đúng hạn và hạn chế tình trạng nhầm lẫn giữa các phiên bản tài liệu.",
                                   "VII. Kết luận và bài học kinh nghiệm",
                                   "Cộng tác trực tuyến không chỉ là việc sử dụng các công cụ số, mà còn là cách tổ chức công việc, giao tiếp và quản lý thông tin một cách khoa học.",
                                   "Thông qua bài tập, có thể rút ra rằng mỗi công cụ nên được sử dụng đúng chức năng: Trello để quản lý tiến độ, Google Drive để lưu trữ, Google Docs để soạn thảo chung và Discord để trao đổi nhanh. Khi các công cụ được kết hợp hợp lý, hiệu quả làm việc nhóm được cải thiện rõ rệt.",
                                   "Bài học cốt lõi: Làm việc nhóm trực tuyến hiệu quả cần có phân công rõ ràng, kênh trao đổi phù hợp, quy tắc quản lý tài liệu thống nhất và thói quen cập nhật tiến độ thường xuyên."
                               ],
                      "images":  [
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUACY13E0NPYGKfjJ8A7hXfSVNKHYfJl8AbNo-pnR3FN1wzUK6KZntGHENiXIzfJmQybBBDP7-0Kay3JKRnnNNW1BzCwzC5UbPx4BvSOug7_OGDfvDF9TfremOxNFsPBFdnYN4BMrWlPo_hczkxFCmkrbSIeQpEFQo_WjVrlGQeAxJaDob6zsQ6ysi_oWqQ56DB-GGzqOE9TDZM06fta7FbcE9EPLNmykM_35dfLf3I=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUDb3WhcTxjz3jqLHCGSsiP3ux6u_efsh9WCPgaQPRqh-mWWMy_QrY0hF3iT2seBx2215BC8mv7pA_ERfk7yXk_bRRm6lZZ8-FII401lBTQhSxQod2GGfMDKGQjOxewZZ7zIwjSKP5w8H4Dwh9shzxlw4xXxiLH8nRWUaDjXks1wHB6wHCcfyU6MSZFAbsU=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUC4yodJ9-nw_kRKFhtVBK1YjREAoH_JrbqhAVOP0HX1_h3K64XIhb6bI-R-s5iYgja2EOPhrc8bqF3gSt_1jo9oHixIiVWX25E29hrwU6Y7vS_r1-52j_cND1isK8ZlxFfB38sHVXBXMjMiZQp70rMnc_QK6lsd3HdEaLc-mId-4s3B6U8kDNObvMJNIMtMXS_i-6xjGXKFSYUVT6XUmbQIcKHL0H0Q-Ww7ZOHe4bw=w1280"
                                 ]
                  },
                  {
                      "slug":  "bai-5",
                      "section":  "Bài 5",
                      "title":  "Portfolio - Bài 5 : Sử dụng AI tạo sinh để hỗ trợ sáng tạo nội dung",
                      "description":  "Giới thiệu bài tập\nBài tập này tập trung vào việc sử dụng trí tuệ nhân tạo để hỗ trợ quá trình sáng tạo nội dung số. Sản phẩm được thực hiện là một Infographic về chủ đề “Tác động của AI đối với các ngành nghề trong tương lai”.\nNội dung bài tập bao gồm lên ý tưởng, xây dựng dàn ý, tạo hình ảnh minh",
                      "sourceUrl":  "https://sites.google.com/view/25020163-phamviethoang/ii-dự-án-học-tập/bài-5-sử-dụng-ai-tạo-sinh-để-hỗ-trợ-sáng-tạo-nội-dung",
                      "text":  [
                                   "Bài 5: Sử dụng AI tạo sinh để hỗ trợ sáng tạo nội dung",
                                   "Giới thiệu bài tập",
                                   "Bài tập này tập trung vào việc sử dụng trí tuệ nhân tạo để hỗ trợ quá trình sáng tạo nội dung số. Sản phẩm được thực hiện là một Infographic về chủ đề “Tác động của AI đối với các ngành nghề trong tương lai”.",
                                   "Nội dung bài tập bao gồm lên ý tưởng, xây dựng dàn ý, tạo hình ảnh minh họa, thiết kế sản phẩm trên Canva và đánh giá vai trò của AI trong quá trình sáng tạo. Qua đó, người học rèn luyện khả năng kết hợp giữa công cụ AI và tư duy cá nhân để tạo ra một sản phẩm truyền thông trực quan.",
                                   "Thông tin bài tập",
                                   "• Chủ đề: Sáng tạo nội dung số với trí tuệ nhân tạo",
                                   "• Tên dự án: Tác động của AI đối với các ngành nghề trong tương lai",
                                   "• Sản phẩm thực hiện: Infographic",
                                   "• Công cụ sử dụng: Gemini, DALL-E 3 và Canva",
                                   "• Nội dung chính: Lên ý tưởng, tạo nội dung, tạo hình ảnh minh họa, thiết kế Infographic và đánh giá vai trò của AI",
                                   "Mục tiêu và kỹ năng đạt được",
                                   "• Lên ý tưởng nội dung: Biết sử dụng AI để gợi ý chủ đề, xây dựng dàn ý và định hướng nội dung.",
                                   "• Tạo hình ảnh minh họa: Biết viết prompt để tạo hình ảnh phù hợp với phong cách sản phẩm.",
                                   "• Thiết kế sản phẩm số: Biết sử dụng Canva để chỉnh sửa bố cục, font chữ, màu sắc và hình ảnh.",
                                   "• Tư duy phản biện: Biết đánh giá điểm mạnh, hạn chế và rủi ro khi sử dụng AI trong sáng tạo nội dung.",
                                   "• Trách nhiệm số: Biết cân nhắc vấn đề bản quyền, tính cá nhân và sự phụ thuộc vào AI.",
                                   "I. Giới thiệu dự án sáng tạo nội dung số",
                                   "Việc lựa chọn chủ đề phù hợp giúp sản phẩm số có tính thực tiễn, gần gũi với người học và phản ánh đúng bối cảnh công nghệ hiện nay.",
                                   "Dự án được thực hiện với tên gọi “Tác động của AI đối với các ngành nghề trong tương lai”. Đây là chủ đề có tính thời sự vì trí tuệ nhân tạo đang ảnh hưởng mạnh đến thị trường lao động, cách làm việc và yêu cầu kỹ năng của con người trong tương lai.",
                                   "Mục tiêu của dự án là tạo ra một Infographic ngắn gọn, dễ hiểu và có tính trực quan, giúp sinh viên và người đi làm có cái nhìn tổng quan về sự thay đổi của nghề nghiệp trong thời đại AI.",
                                   "II. Lên ý tưởng và xây dựng nội dung bằng Gemini",
                                   "Gemini được sử dụng ở giai đoạn đầu để hỗ trợ xây dựng cấu trúc nội dung cho Infographic. Việc dùng prompt rõ ràng giúp AI đưa ra dàn ý có định hướng hơn thay vì chỉ trả lời chung chung.",
                                   "1. Prompt ban đầu:",
                                   "\"Viết về tác động của AI đối với công việc.\"",
                                   "2. Prompt chuyên sâu:",
                                   "\"Đóng vai một chuyên gia phân tích xu hướng công nghệ, hãy lập dàn ý nội dung cho một Infographic về chủ đề \u0027Tác động của AI đối với các ngành nghề trong tương lai\u0027. Yêu cầu: Nội dung chia làm 5 phần rõ rệt, ngôn ngữ súc tích, hiện đại, phù hợp cho sinh viên và người đi làm. Mỗi phần kèm theo một gợi ý về hình ảnh minh họa.\"",
                                   "Minh chứng : Sử dụng Gemini để xây dựng dàn ý nội dung cho Infographic.",
                                   "Prompt chuyên sâu hiệu quả hơn prompt ban đầu vì có vai trò, chủ đề, đối tượng người xem, số phần nội dung và yêu cầu hình ảnh minh họa. Nhờ đó, kết quả AI tạo ra có cấu trúc rõ ràng hơn và dễ chuyển sang bước thiết kế.",
                                   "III. Tạo hình ảnh minh họa bằng DALL-E 3",
                                   "Hình ảnh minh họa giữ vai trò quan trọng trong Infographic vì giúp nội dung trở nên trực quan và thu hút hơn. DALL-E 3 được sử dụng để thử nghiệm các prompt tạo hình ảnh theo phong cách công nghệ tương lai.",
                                   "1. Prompt lần 1:",
                                   "\"A futuristic office\"",
                                   "Kết quả: Hình ảnh còn khá chung chung, chưa làm nổi bật được sự tương tác giữa con người và AI.",
                                   "2. Prompt lần 2:",
                                   "\"A futuristic office, cinematic lighting, 3D render style, vibrant colors, human and robot working together\"",
                                   "Kết quả: Hình ảnh có ánh sáng, màu sắc và phong cách hiện đại hơn, phù hợp hơn với định hướng Infographic.",
                                   "So sánh hai lần tạo ảnh cho thấy prompt càng cụ thể thì hình ảnh càng sát mục tiêu. Việc bổ sung các yếu tố như ánh sáng, phong cách 3D, màu sắc và sự tương tác giữa người với robot giúp hình ảnh có tính biểu tượng rõ hơn.",
                                   "IV. Thiết kế và hoàn thiện sản phẩm bằng Canva",
                                   "Sau khi có dàn ý nội dung và hình ảnh minh họa, Canva được sử dụng để thiết kế và hoàn thiện Infographic. Quá trình này không chỉ dựa vào gợi ý của AI mà còn cần chỉnh sửa thủ công để bảo đảm tính thẩm mỹ và dấu ấn cá nhân.",
                                   "Các thao tác chỉnh sửa chính gồm:",
                                   "1. Chọn và điều chỉnh bố cục phù hợp với nội dung Infographic.",
                                   "2. Sửa font chữ để tiêu đề rõ ràng, dễ đọc và phù hợp với phong cách công nghệ.",
                                   "3. Điều chỉnh màu sắc để tạo sự thống nhất cho toàn bộ thiết kế.",
                                   "4. Kéo thả, căn chỉnh các thành phần hình ảnh và nội dung để bố cục cân đối hơn.",
                                   "Minh chứng : Chỉnh sửa font chữ, màu sắc và bố cục Infographic trên Canva.",
                                   "V. Phân tích vai trò của AI trong dự án",
                                   "AI đóng vai trò là công cụ hỗ trợ trong quá trình sáng tạo nội dung, nhưng không thay thế hoàn toàn vai trò của người thực hiện.",
                                   "Trong dự án này, AI hỗ trợ ở nhiều giai đoạn khác nhau. Gemini giúp gợi ý dàn ý, xây dựng nội dung và mở rộng góc nhìn về chủ đề. DALL-E 3 hỗ trợ tạo hình ảnh minh họa theo phong cách công nghệ. Canva giúp hoàn thiện sản phẩm bằng các công cụ thiết kế trực quan.",
                                   "Tuy nhiên, người thực hiện vẫn giữ vai trò quyết định trong việc lựa chọn thông tin, chỉnh sửa bố cục, kiểm tra nội dung và bảo đảm sản phẩm cuối cùng phù hợp với mục tiêu ban đầu.",
                                   "VI. Hạn chế, đạo đức và bản quyền khi sử dụng AI",
                                   "Bên cạnh lợi ích, việc sử dụng AI trong sáng tạo nội dung cũng cần được xem xét cẩn thận về độ chính xác, tính phụ thuộc và vấn đề bản quyền.",
                                   "Một số hạn chế cần lưu ý:",
                                   "• Nội dung do AI tạo ra có thể còn chung chung hoặc chưa phù hợp hoàn toàn với mục tiêu của sản phẩm.",
                                   "• Hình ảnh do AI tạo ra có thể đẹp nhưng chưa chắc truyền tải đúng thông điệp nếu prompt chưa đủ rõ.",
                                   "• Người dùng không nên phụ thuộc hoàn toàn vào AI mà cần kiểm tra, chọn lọc và chỉnh sửa kết quả.",
                                   "Về đạo đức và bản quyền:",
                                   "AI nên được xem là công cụ hỗ trợ sáng tạo. Sản phẩm cuối cùng cần thể hiện dấu ấn cá nhân thông qua việc lựa chọn nội dung, sắp xếp bố cục, kiểm định thông tin và chỉnh sửa thiết kế.",
                                   "VII. Kết luận và bài học kinh nghiệm",
                                   "Dự án sáng tạo nội dung số cho thấy AI có thể hỗ trợ hiệu quả trong nhiều giai đoạn, từ lên ý tưởng, tạo nội dung, tạo hình ảnh đến hoàn thiện thiết kế. Tuy nhiên, AI chỉ nên được xem là công cụ hỗ trợ, còn người học vẫn cần giữ vai trò kiểm soát, chọn lọc và sáng tạo.",
                                   "Thông qua bài tập, có thể rút ra rằng một sản phẩm số tốt không chỉ phụ thuộc vào công cụ AI mà còn phụ thuộc vào cách đặt prompt, khả năng đánh giá kết quả và kỹ năng chỉnh sửa của người thực hiện.",
                                   "Bài học cốt lõi: AI có thể cung cấp nguyên liệu nhanh chóng, nhưng con người là người quyết định cách sử dụng, sắp xếp và hoàn thiện những nguyên liệu đó thành một sản phẩm có ý nghĩa."
                               ],
                      "images":  [
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUC_M_QQ4Nyr8hrgJchKmCCejsQw_W-i2M30rQ5LvQU22Wn8yuySSaLAQKEGBIO89HR2RjWYPsmoxbTGPPDu-Dv1MJK4YSW7gmZDiLWyYnJ3SRs9DN1x9pFC_9qmmwLaCHKdxooMjGnurHmufL_JvZwQa24UT_QvuUTdmth-nI8dn8jzK1pUfaReC1tWJqbPxqTGwNN-1eIp-lswoOAHJrJ-C0OEpiwuzHjGA4BWYeQ=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUDdFt5q0YXNHkLsSgBwNdBF6l5_sP_UULtOpTaVgWkUIcau-ii1aDhZuJi9OaNgnO_4Qxo1GEgH6eGr3TxqrnQKehGmRSIUWh6p4wiuhf47g9EDuI8bUTqwZ50NN-aW7fB5oYrfoUEXByzMvDe7kiaSsz2AdPyB0nJTaWPVY7cy9ljeVxAe8MNpIYTiR0sElrbE6KUHde7SUp_SZ-maraNjfuBVDZQ-_S_gzkyI=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUCny1MdIHPfsBvz7-bvphzNi2yec5d7knVpv80sB8l3Uep6L-lbxYJgV5PfhOWqWsJ-UZ5-TrNI31TZDgmH76OvkyLsEB_eyPyE46-ij4bKu2b31c9A7YhKrstfGb09jGKh5G5L2rkuM4j_ESy474T3DRa3eDlshiv4mSPJSnU5quGJNvABDsJyLpio99CvvD5oafKea_BHtPfQlC9V1CmdF_qIHVxVwQ1sa6HL1Ys=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUCWLwErQeG54aShTZCuu9Rqj2S66Ymtluba-FJytfRhtI9dAPp75-Pn3I-kmEGTg0Af80cUAOAupxiXrXHhqcQVsivFuSwKj2CGTrP-9SFOA6svevp1_wNrxBfzJWnZuhU256o_b5dC6SDieXLHsUUa13i3bCnFcBKQMUPYxomW-Yi_xE5cgoumJeVG54nT6pZpEvwl8n-WIygDkw0NHtcZ7Q5Upr4WPpyw7pFHkEs=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUCsfEUDBJTBMTtYU9UrENDbpnGMFljrR7LzhivB7-8u6XujL1GWrS24PxvMyjsceAYrlqIlbtTKW9KX-4aRymR9iyul2ZJg6HOrKZTgNYxr-6zV6zCBAT8NeCG2QxtYaqAM72Vch1NqwZ9zuYWOUm9j-I9Pxw0HpHTzX7Xgwae4hhZVtLrAezAJHGjujgkm6HGmVHr0RbJ0bOj6wQP0RYEn89MNZCw-3DlhnWByZ3s=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUATWntdKOA3Q_dFGFZo5XKu8s8qNSO1nm4lnorWxMZLqRWyfbHhqEaDIij4rwpyOyxtUwlifHzCTJUXZCJVCrA1KPSkUPYnH5Br_GnEtnhZZEkVr7uMsFcV1a1HVYhCHsoN3kPgw6rTgLnp1_T-mHJoXoyWCb3lxqJbl7MMOsHOz5UQTjup6re6P9WCxDqlru27gk5MJe6echer2FRgnqsUWsU8IMdZUHcyC_jk=w1280"
                                 ]
                  },
                  {
                      "slug":  "bai-6",
                      "section":  "Bài 6",
                      "title":  "Portfolio - Bài 6 : Sử dụng AI có trách nhiệm trong học tập và nghiên cứu",
                      "description":  "Giới thiệu bài tập\nBài tập này tập trung vào việc tìm hiểu và thực hành sử dụng trí tuệ nhân tạo một cách có trách nhiệm trong học thuật. Nội dung thực hiện bao gồm nghiên cứu chính sách sử dụng AI, ghi lại quá trình sử dụng AI trong một nhiệm vụ học tập, phân tích các vấn đề đạo đức và xây dựng",
                      "sourceUrl":  "https://sites.google.com/view/25020163-phamviethoang/ii-dự-án-học-tập/bài-6-sử-dụng-ai-có-trách-nhiệm-trong-học-tập-và-nghiên-cứu",
                      "text":  [
                                   "Bài 6: Sử dụng AI có trách nhiệm trong học tập và nghiên cứu",
                                   "Giới thiệu bài tập",
                                   "Bài tập này tập trung vào việc tìm hiểu và thực hành sử dụng trí tuệ nhân tạo một cách có trách nhiệm trong học thuật. Nội dung thực hiện bao gồm nghiên cứu chính sách sử dụng AI, ghi lại quá trình sử dụng AI trong một nhiệm vụ học tập, phân tích các vấn đề đạo đức và xây dựng nguyên tắc cá nhân khi dùng AI.",
                                   "Thông qua bài tập, người học rèn luyện tư duy phản biện, ý thức trung thực học thuật và khả năng kiểm soát công cụ AI. AI được xem là công cụ hỗ trợ học tập, nhưng người học vẫn cần tự kiểm chứng, chỉnh sửa và chịu trách nhiệm với sản phẩm cuối cùng.",
                                   "Thông tin bài tập",
                                   "• Chủ đề: Sử dụng AI có trách nhiệm trong học thuật",
                                   "• Nhiệm vụ thực hiện: Xây dựng Infographic “Tác động của AI đối với các ngành nghề trong tương lai”",
                                   "• Công cụ sử dụng: Gemini và Canva",
                                   "• Nội dung chính: Nghiên cứu chính sách AI, ghi nhật ký sử dụng AI, phân tích đạo đức và xây dựng nguyên tắc sử dụng AI có trách nhiệm",
                                   "Mục tiêu và kỹ năng đạt được",
                                   "• Nhận thức chính sách: Hiểu được yêu cầu về liêm chính học thuật khi sử dụng AI trong học tập.",
                                   "• Sử dụng AI minh bạch: Biết ghi lại quá trình dùng AI và xác định rõ phần nào có sự hỗ trợ của AI.",
                                   "• Tư duy phản biện: Biết kiểm tra, đánh giá và chỉnh sửa kết quả do AI tạo ra.",
                                   "• Trách nhiệm học thuật: Biết phân biệt ranh giới giữa hỗ trợ học tập và gian lận.",
                                   "• Bảo mật và đạo đức số: Biết tránh chia sẻ dữ liệu nhạy cảm và sử dụng AI có trách nhiệm.",
                                   "I. Nghiên cứu chính sách sử dụng AI",
                                   "Việc tìm hiểu chính sách sử dụng AI giúp người học nhận thức rõ giới hạn được phép và không được phép khi ứng dụng AI trong học tập, từ đó bảo đảm tính trung thực và trách nhiệm học thuật.",
                                   "Trong bối cảnh học thuật, AI có thể được sử dụng để hỗ trợ gợi ý ý tưởng, xây dựng cấu trúc bài viết hoặc giải thích các khái niệm phức tạp. Tuy nhiên, việc sao chép hoàn toàn nội dung do AI tạo ra mà không kiểm chứng hoặc không minh bạch là hành vi không phù hợp với nguyên tắc liêm chính học thuật.",
                                   "Bài báo cáo cũng so sánh định hướng sử dụng AI giữa VNU-UET và Stanford University. Cả hai đều không cấm tuyệt đối việc sử dụng AI, nhưng đều nhấn mạnh yêu cầu minh bạch, trách nhiệm cá nhân và ranh giới giữa hỗ trợ học tập với gian lận.",
                                   "Minh chứng : Nghiên cứu và so sánh chính sách sử dụng AI trong học thuật.",
                                   "II. Nhật ký sử dụng AI trong nhiệm vụ học tập",
                                   "Ghi lại quá trình sử dụng AI giúp thể hiện sự minh bạch, đồng thời cho thấy AI đã hỗ trợ ở giai đoạn nào và người học đã can thiệp, chỉnh sửa ra sao.",
                                   "Nhiệm vụ được lựa chọn là xây dựng Infographic “Tác động của AI đối với các ngành nghề trong tương lai”.",
                                   "Ở giai đoạn đầu, Gemini được sử dụng để hỗ trợ lên kịch bản và dàn ý. Prompt khởi tạo được sử dụng là: “Đóng vai chuyên gia, lập dàn ý Infographic 5 phần về tác động của AI đến nghề nghiệp.”",
                                   "Kết quả ban đầu khá đầy đủ nhưng vẫn còn chung chung, vì vậy nội dung tiếp tục được tinh chỉnh để phù hợp hơn với mục tiêu của sản phẩm.",
                                   "Minh chứng : Ghi lại quá trình sử dụng Gemini để lên dàn ý cho Infographic.",
                                   "III. Tinh chỉnh kết quả AI bằng tư duy cá nhân",
                                   "Sử dụng AI có trách nhiệm không dừng lại ở việc nhận kết quả từ công cụ, mà cần có sự đánh giá, điều chỉnh và bổ sung bằng tư duy cá nhân.",
                                   "Sau khi nhận kết quả ban đầu từ Gemini, nội dung tiếp tục được điều chỉnh bằng yêu cầu cụ thể hơn: “Phần 4 cần tập trung sâu hơn vào vấn đề đạo đức tại Việt Nam, hãy viết lại súc tích hơn.”",
                                   "Việc tinh chỉnh này cho thấy người học không phụ thuộc hoàn toàn vào AI, mà sử dụng AI như một công cụ hỗ trợ để cải thiện nội dung theo mục tiêu đã xác định.",
                                   "Minh chứng : Tinh chỉnh kết quả AI để nội dung phù hợp hơn với bối cảnh Việt Nam.",
                                   "IV. Thiết kế và phối hợp công cụ bằng Canva",
                                   "Sau khi có dàn ý từ Gemini, Canva được sử dụng để hỗ trợ thiết kế sản phẩm Infographic. Tuy nhiên, thiết kế cuối cùng vẫn cần sự can thiệp của người thực hiện để phù hợp với mục tiêu học thuật.",
                                   "Canva Magic Design được sử dụng để gợi ý bố cục dựa trên dàn ý đã có. Tuy nhiên, kết quả ban đầu chưa hoàn toàn phù hợp, đặc biệt là màu sắc còn rực rỡ và chưa đúng với phong cách học thuật.",
                                   "Người thực hiện đã chủ động thay đổi bảng màu sang tông xanh - trắng chuyên nghiệp, sắp xếp lại biểu tượng minh họa và biên tập lại một phần nội dung để phù hợp hơn với bối cảnh sinh viên VNU-UET.",
                                   "Minh chứng : Sử dụng Canva và chỉnh sửa thủ công để hoàn thiện sản phẩm.",
                                   "V. Phân tích các vấn đề đạo đức khi sử dụng AI",
                                   "Trong học thuật, sử dụng AI cần gắn với các vấn đề đạo đức như trung thực, sở hữu trí tuệ, sự phụ thuộc và trách nhiệm cá nhân.",
                                   "Một số vấn đề đạo đức cần lưu ý gồm:",
                                   "• Ranh giới giữa hỗ trợ và gian lận: AI chỉ nên hỗ trợ gợi ý, phản biện hoặc định hướng nội dung. Gian lận xảy ra khi người học để AI viết toàn bộ sản phẩm và nộp như kết quả tự thân.",
                                   "• Sở hữu trí tuệ: Nội dung và hình ảnh do AI tạo ra có thể dựa trên dữ liệu lớn từ nhiều nguồn khác nhau, vì vậy cần có sự chỉnh sửa, lựa chọn và sáng tạo cá nhân.",
                                   "• Sự lệ thuộc: Việc phụ thuộc quá mức vào AI có thể làm giảm tư duy phản biện, khả năng viết độc lập và năng lực tự học của sinh viên.",
                                   "VI. Bộ nguyên tắc sử dụng AI có trách nhiệm",
                                   "Từ quá trình thực hành, có thể xây dựng một bộ nguyên tắc cá nhân nhằm sử dụng AI minh bạch, an toàn và hiệu quả hơn trong học tập.",
                                   "Bộ 7 nguyên tắc sử dụng AI có trách nhiệm:",
                                   "1. Nguyên tắc 70/30: AI chỉ hỗ trợ tối đa 30% nội dung thô, 70% còn lại là tư duy, kiểm chứng và chỉnh sửa cá nhân.",
                                   "2. Kiểm chứng bắt buộc: Mọi số liệu, ngày tháng hoặc nhận định quan trọng do AI cung cấp cần được đối chiếu với nguồn đáng tin cậy.",
                                   "3. Minh bạch trích dẫn: Ghi rõ các phần có sự hỗ trợ của AI khi cần thiết.",
                                   "4. Không cung cấp dữ liệu nhạy cảm: Không nhập thông tin cá nhân, tài khoản, mật khẩu hoặc dữ liệu nội bộ vào công cụ AI công cộng.",
                                   "5. Tư duy phản biện: Luôn đặt câu hỏi ngược lại cho kết quả AI để phát hiện lỗi sai, thiên kiến hoặc nội dung chưa phù hợp.",
                                   "6. Sáng tạo không rập khuôn: Không sử dụng nguyên mẫu kết quả AI mà cần tùy chỉnh để thể hiện dấu ấn cá nhân.",
                                   "7. Cập nhật liên tục: Theo dõi các quy định mới về sử dụng AI để điều chỉnh hành vi học tập cho phù hợp.",
                                   "VII. Kết luận và bài học kinh nghiệm",
                                   "Việc sử dụng AI trong học tập giúp thay đổi quy trình làm việc từ tìm ý tưởng thủ công sang lọc, kiểm chứng và tối ưu hóa ý tưởng. Tuy nhiên, AI cũng có thể đưa ra những gợi ý chưa phù hợp, vì vậy người học cần biết phát hiện lỗi sai, chỉnh sửa và kiểm soát kết quả.",
                                   "Thông qua bài tập, có thể rút ra rằng AI chỉ phát huy hiệu quả khi được sử dụng minh bạch và có trách nhiệm. Người học cần biết đặt yêu cầu rõ ràng, kiểm chứng thông tin, bảo vệ dữ liệu cá nhân và không sao chép máy móc kết quả do AI tạo ra.",
                                   "Bài học cốt lõi: AI không thay thế tư duy của người học. AI chỉ là công cụ hỗ trợ, còn chất lượng sản phẩm cuối cùng phụ thuộc vào khả năng chọn lọc, phản biện và sáng tạo của con người."
                               ],
                      "images":  [
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUBxGSzgtu3rKpVRauAhPPqCzeRihkiV8RX0mD0LjR5w7QuvbYErqEfJpJLEc9XZZwO4utik9QF3HJ-9bp98EJXbYc3l-fkofY92KOaHaFLDiACYmGN7ZA-EbXvPfqgYNgAZrYgc_IYvgxnG0h_glRgxmhAqkcO-MzEIcsXmtOQkwHwt-5Mb-fx9WnmsvH6LS819OoGUrSpl0Gloho_vJJWSVL4wP1ulPfxUydd7kiw=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUCXiLsX7y1o5YcSPSz0L4hjtFkdTnHwuEyna5L_wICPZZNceY5mXaNkDdeRw4Riwp_CQC0s2V2iBf-T7F1-8iFEefMNu-GfsbrdYN2fVnAIalR2gPGrKqyeX7N5021JjJUKVaGampCZ4XUzIHJEPue5ffp6S7rA0XTeGEDmgRBXsj9xmBOjIvu3uvhvUCTPTeEwp0ZSbND2bs9nm9gTUoXyXuv9nfsvwAoeXnNhTTE=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUAYk97rcZI39nTfE_eUMio8XkjUCuZNqjmZAyEIyNEnLx-5D4ACi7tijJs5Vf-YIYaUlMco-EceGp3nfj3Ylhx07yq1By-SBTn4PaX8OePU3wbJlsbD6fJAz_gi72eacHg-LzdRLjE0_dORwcK-LvqivJq-gaC1Ty1R0JCNQ0RXD0Dt5r9Jm2Z2Y9M6n6Fti0cwodMfZFb-RaHriPIJ6P22ZeYrOLt-mVX-A-FrQNg=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUDhu3eGHjl2nJ--FJoZkNcgO3LxsChJNV6Xfn1XJA002qSDNGLDxzq6pK5IV14rgZXoMa3xbBPzS7PcHXln0G-7H-sSzAj1ffMygcAhgBcs9v8rNrYeO9NkETzLcv8pXakY859LeKpe0xK_HIZTBfOdiS1m8rRy4nMfrsPMLECnImL7iLPDB1S6RJhUO7GfvF5Uizfdpf4m0tgGuQa0NKpXc_a0rYREq7MimSVnyUk=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUCeWLHzKrCMz5ArHpgVh9bhGZn6vJSUqKffCu6kv73l3SbdtaOz_uD1zz3iECLc9TGt6wwoiD3DFv5Tp7EDQg5iF3gKhtb5AVEzhYNFO80yQBLvJZIzP0LOmdQZvL6pXt5fqSEAGeL6N3Dj3TwxVSiJRYh8RU8wS3i_kvysQOHkWmaOQ_NnnMeb2WTUVXo-ROvD1RTe6w3vqBb5C8tEAdSdIXZNeBawzzVFsmdW7G4=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUBnWlHncIBJNyOFF0CY6F0VQqnNpwLhb0cM0tSxA2MRk_ybD5N4IkEqJEVqi4cVAp1e4iTGGuu4-G8VLyxwsqPMP8UiTdELxPWtHdX6fbAinsG4HmGDI2BvcQyrQumg_4cstZtLlHkgYCSVeKNsYimMJJDZmEPYYwLsTIwhuqozN2fP7QIQhSHvWSvzBiE6GMoghYofwnHKHQxI1_uthNcu3Sj-0wO_MlFxExDtyuE=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUAuEPmAg1f8OBbnJCI7N3tX6LHchdHtzOwGk6udnvW2JvCVmujDR6rgxWqfUIsdgicetJeQ_6QSEXCzobTn2VjzI9jf5pjcuR1DvM4xB7N93ey57huv78_THi1_6VfepaQcw-5zxfEezFx1NzdtET1JVx4bvbjAs8v_L0bsUn6_Cf3xxPPDmBAUoFD43jLy1MPPslEhG6fIVq3u9YQdRSA_9bDEu-4Xw70zhRmLUzU=w1280",
                                     "https://lh3.googleusercontent.com/sitesv/AA5AbUCnj9jb0njrG74t0QhktXvU7VYkmNDzGSzrq-RnxWbhTduKx4Lr1b4s5KlKbpR3fcvzrZ8ApmOuq2WBsfBoVVyPrLGnW1FHzpEoFeDWJnNkh5BcVzToDS-Ul3StFt7-XvC1tF38xfxgnso_tusjlD3I_GNrQj0D6i-P0Bcfv46yoHr18N9D0rLlory--4y9EYE5XKTptd9aBOo8COUz69lAo_EJXf527E2SB3UO=w1280"
                                 ]
                  },
                  {
                      "slug":  "summary",
                      "section":  "III. Tổng kết",
                      "title":  "Portfolio - III. Tổng kết",
                      "description":  "Tổng kết Portfolio học tập\nTrang tổng kết này được xây dựng nhằm nhìn lại toàn bộ quá trình thực hiện các bài tập trong học phần Nhập môn Công nghệ số và Ứng dụng Trí tuệ nhân tạo. Thông qua các bài thực hành, người học có cơ hội rèn luyện nhiều kỹ năng quan trọng như quản lý dữ liệu, tìm kiếm",
                      "sourceUrl":  "https://sites.google.com/view/25020163-phamviethoang/iii-tổng-kết",
                      "text":  [
                                   "Tổng kết Portfolio học tập",
                                   "Trang tổng kết này được xây dựng nhằm nhìn lại toàn bộ quá trình thực hiện các bài tập trong học phần Nhập môn Công nghệ số và Ứng dụng Trí tuệ nhân tạo. Thông qua các bài thực hành, người học có cơ hội rèn luyện nhiều kỹ năng quan trọng như quản lý dữ liệu, tìm kiếm thông tin học thuật, viết prompt, cộng tác trực tuyến, sáng tạo nội dung số và sử dụng AI có trách nhiệm.",
                                   "Portfolio không chỉ là nơi lưu trữ sản phẩm học tập, mà còn thể hiện quá trình tự học, tự đánh giá và phát triển kỹ năng số của bản thân trong môi trường học tập hiện đại.",
                                   "I. Tổng quan quá trình học tập",
                                   "Trong quá trình thực hiện Portfolio, sáu bài tập chính đã được hoàn thành theo từng chủ đề khác nhau. Mỗi bài tập tập trung vào một nhóm kỹ năng cụ thể, từ thao tác cơ bản với máy tính đến ứng dụng trí tuệ nhân tạo trong học tập và sáng tạo nội dung.",
                                   "Các bài tập được trình bày theo cấu trúc thống nhất gồm giới thiệu bài tập, thông tin bài tập, mục tiêu kỹ năng, quy trình thực hiện, minh chứng và kết luận. Cách trình bày này giúp người xem dễ theo dõi quá trình thực hiện và đánh giá được kết quả học tập.",
                                   "II. Những kỹ năng đã rèn luyện được",
                                   "Thông qua quá trình thực hiện các bài tập, nhiều kỹ năng số quan trọng đã được rèn luyện và cải thiện.",
                                   "• Kỹ năng quản lý tập tin và thư mục: Biết tạo thư mục, đổi tên, sao chép, di chuyển, xóa và khôi phục dữ liệu trên Windows.",
                                   "• Kỹ năng tìm kiếm thông tin học thuật: Biết xác định chủ đề, xây dựng từ khóa, lựa chọn nguồn tin và đánh giá độ tin cậy của tài liệu.",
                                   "• Kỹ năng viết prompt: Biết thiết kế câu lệnh rõ ràng, có ngữ cảnh, có vai trò, có đối tượng và có định dạng đầu ra cụ thể.",
                                   "• Kỹ năng cộng tác trực tuyến: Biết sử dụng Trello, Google Drive, Google Docs và Discord để phối hợp trong dự án nhóm.",
                                   "• Kỹ năng sáng tạo nội dung số: Biết sử dụng AI để hỗ trợ lên ý tưởng, tạo hình ảnh minh họa và thiết kế sản phẩm bằng Canva.",
                                   "• Kỹ năng sử dụng AI có trách nhiệm: Biết kiểm chứng thông tin, bảo vệ dữ liệu cá nhân, minh bạch khi sử dụng AI và tránh phụ thuộc hoàn toàn vào AI.",
                                   "III. Tự đánh giá kết quả học tập",
                                   "Sau khi hoàn thành Portfolio, em tự đánh giá quá trình học tập theo ba khía cạnh: điểm mạnh, điểm cần cải thiện và mức độ hoàn thành mục tiêu.",
                                   "Điểm mạnh:",
                                   "• Hoàn thành đầy đủ các bài tập theo yêu cầu của học phần.",
                                   "• Biết trình bày sản phẩm học tập theo cấu trúc rõ ràng, có minh chứng cụ thể.",
                                   "• Biết kết hợp nhiều công cụ số như Google Sites, Google Drive, Canva, Trello, Discord và các công cụ AI.",
                                   "• Có khả năng so sánh, đánh giá và rút ra bài học sau mỗi hoạt động thực hành.",
                                   "• Biết sử dụng AI theo hướng hỗ trợ, có kiểm chứng và có chỉnh sửa cá nhân.",
                                   "Điểm cần cải thiện:",
                                   "• Cần tiếp tục cải thiện kỹ năng thiết kế giao diện để Portfolio chuyên nghiệp hơn.",
                                   "• Cần luyện tập thêm cách trích dẫn nguồn học thuật và trình bày tài liệu tham khảo.",
                                   "• Cần nâng cao khả năng kiểm chứng thông tin khi sử dụng AI.",
                                   "• Cần quản lý thời gian tốt hơn khi thực hiện các bài tập dài hoặc có nhiều minh chứng.",
                                   "Mức độ hoàn thành:",
                                   "Nhìn chung, Portfolio đã hoàn thành các nội dung chính của học phần. Các bài tập đều có phần giới thiệu, mục tiêu, quy trình thực hiện, minh chứng và phần kết luận. Qua đó, Portfolio thể hiện được quá trình học tập, khả năng sử dụng công cụ số và ý thức trách nhiệm khi ứng dụng AI.",
                                   "IV. Định hướng phát triển sau học phần",
                                   "Sau khi hoàn thành học phần, các kỹ năng đã học có thể tiếp tục được áp dụng trong quá trình học tập và làm việc sau này.",
                                   "Trong thời gian tới, tiếp tục rèn luyện kỹ năng sử dụng công cụ số để quản lý tài liệu học tập hiệu quả hơn. Việc tổ chức thư mục, đặt tên tệp và lưu trữ dữ liệu khoa học sẽ giúp quá trình học tập trở nên thuận tiện và chuyên nghiệp hơn.",
                                   "Bên cạnh đó, cần tiếp tục phát triển kỹ năng tìm kiếm, đánh giá và kiểm chứng thông tin. Đây là kỹ năng quan trọng đối với sinh viên Công nghệ thông tin, đặc biệt trong bối cảnh thông tin trên Internet rất đa dạng và không phải nguồn nào cũng đáng tin cậy.",
                                   "Đối với trí tuệ nhân tạo, cần sử dụng AI như một công cụ hỗ trợ học tập có chọn lọc. AI có thể giúp gợi ý ý tưởng, giải thích kiến thức và hỗ trợ sáng tạo nội dung, nhưng người học vẫn cần giữ vai trò chủ động trong việc kiểm tra, chỉnh sửa và chịu trách nhiệm với sản phẩm cuối cùng.",
                                   "V. Lời kết",
                                   "Portfolio học tập cá nhân là kết quả tổng hợp của quá trình thực hành, tự học và ứng dụng công nghệ số trong học phần. Qua từng bài tập, người học không chỉ hoàn thành sản phẩm theo yêu cầu mà còn hình thành thói quen làm việc khoa học, có tổ chức và có trách nhiệm hơn.",
                                   "Bài học quan trọng nhất rút ra từ học phần là: công nghệ số và trí tuệ nhân tạo chỉ thật sự phát huy hiệu quả khi người học biết sử dụng chúng một cách chủ động, sáng tạo, trung thực và có kiểm soát.",
                                   "Trong tương lai, những kỹ năng này sẽ tiếp tục là nền tảng quan trọng để phục vụ học tập, nghiên cứu và phát triển nghề nghiệp trong lĩnh vực Công nghệ thông tin."
                               ],
                      "images":  [

                                 ]
                  }
              ]
}
;
