# Th�ng tin c?u h�nh Database Aiven MySQL
db.host=mysql-24dbe87d-team09-uet.c.aivencloud.com
db.port=12014
db.name=defaultdb
db.user=avnadmin
db.password=AVNS_DxKGxvHASiK6mmOKQbm

# C?u h�nh k?t n?i m?ng (S?a th�nh localhost khi test offline, ??i IP Public khi ch?y th?t)
server.ip=127.0.0.1
server.port=8080
