# Thông tin cấu hình CSDL Aiven MySQL
db.host=mysql-24dbe87d-team09-uet.c.aivencloud.com
db.port=12014
db.name=defaultdb
db.user=avnadmin
db.password=AVNS_DxKGxvHASiK6mmOKQbm
db.ssl=true

# Cấu hình kết nối mạng
server.ip=127.0.0.1
server.port=8080
